<?php
/**
 * BelVG
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 
 * @category   Belvg
 * @package    Chameleon Mobile Theme
 * @copyright  Copyright (c) 2010 - 2012 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<?php $_cartItems = $this->helper('checkout/cart')->getSummaryCount(); ?>
<?php 
	$curr = $this->helper('core/url')->getCurrentUrl();
?>
<ul class="user-menu">
	<li class="checkout-icon<?php if ($curr == $this->getUrl('checkout/onepage')): ?> active<?php endif ?>">
		<a href="<?php echo $this->getUrl('checkout/onepage/'); ?>" title="<?php echo $this->__('Checkout') ?>"><span>&nbsp;</span><?php echo $this->__('Checkout') ?></a>
	</li>
    <li class="cart-icon<?php if ($curr == $this->getUrl('checkout/cart')): ?> active<?php endif ?>">
        <a href="<?php echo $this->getUrl('checkout/cart'); ?>" title="<?php echo $this->__('Cart') ?>"><span>&nbsp;<?php echo $_cartItems > 0 ? '<strong>'.$_cartItems.'</strong>' : ''; ?></span><?php echo $this->__('Cart') ?></a>           
    </li>
	<?php if( Mage::getSingleton('customer/session')->isLoggedIn() ): ?> 
	<li class="login-icon">
		<a href="<?php echo $this->getUrl('customer/account/logout') ?>" title="<?php echo $this->__('Log Out') ?>"><span>&nbsp;</span><?php echo $this->__('Login Out') ?></a>
	</li>
		<?php else : ?>
	<li class="login-icon<?php if ($curr == $this->getUrl('customer/account/login')): ?> active<?php endif ?>">
		<a href="<?php echo $this->getUrl('customer/account/login/') ?>" title="<?php echo $this->__('Login') ?>"><span>&nbsp;</span><?php echo $this->__('Login') ?></a>
	</li>
	<?php endif; ?>
	<li class="account-icon<?php if ($curr == $this->getUrl('customer/account')): ?> active<?php endif ?>">
		<a href="<?php echo $this->getUrl('customer/account') ?>" title="<?php echo $this->__('Account') ?>"><span>&nbsp;</span><?php echo $this->__('Account') ?></a>
	</li>
</ul>
	<div class="header">
		<h1 class="logo">
			<!--<a href="<?php //echo $this->getUrl('') ?>" title="<?php //echo $this->getLogoAlt() ?>"><img src="<?php //echo $this->getLogoSrc() ?>" alt="<?php //echo $this->getLogoAlt() ?>" /></a>-->
			<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
			<a id="pink" style="display:none;" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
			<a id="green" style="display:none;" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getSkinUrl('images/logo-green.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
			<a id="brown" style="display:none;" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
			<a id="blue" style="display:none;" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
			<a id="darkblue" style="display:none;" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getSkinUrl('images/logo-darkblue.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
		</h1>
        <dl id="menu" style="display:none;">
            <dt class="menu dropdown"><a href="#"><?php echo $this->__('Menu') ?></a></dt>
            <dd class="menu-box">
                <?php echo $this->getChildHtml('topLinks') ?>
                <?php echo $this->getChildHtml('checkoutLinks') ?>
                <?php echo $this->getChildHtml('accountLinks') ?>
            </dd>
            <dt class="cart-icon <?php echo $this->getInCart() ? 'active' : '' ?>">
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('Cart') ?></a>
                <?php echo $_cartItems > 0 ? '<span>'.$_cartItems.'</span>' : ''; ?>
            </dt>
            <dd></dd>
        </dl>
		<a href="#" class="user-menu-button"><?php echo $this->__('Menu') ?></a>
		<?php echo $this->getChildHtml('store_language') ?> <?php //Store View Switcher ?>      
     	<div class="search-block"><?php echo $this->getChildHtml('topSearch') ?></div>
			<div class="slider">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('slider')->toHtml()  ?>
			</div>
	</div>
	<?php echo $this->getChildHtml('topCart') ?>
	<?php echo $this->getChildHtml('topLinks') ?>