<?php 
$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
if(isset($_GET["todl"]))
{
    $emp="";
    for($ff=1;$ff<=22;$ff++)
	{
	    if(isset($_GET["chk-".$ff]))
		{
		   $emp.=$_GET["chk-".$ff].",";
		}
	}
	
	$sel_gdates="select dated from toadayemp where dated='".date(d_m_Y)."'";
	$check=$connection->fetchOne($sel_gdates);
	
	if($check=="")
	{
	   $insert="insert into toadayemp set dated='".date(d_m_Y)."',emp='".$emp."'";
	   $connection->query($insert);
	}
	
	else
	{
	   $update="update toadayemp set emp='".$emp."' where dated='".date(d_m_Y)."'";
	   $connection->query($update);
	}
}



if(isset($_GET["detl"]))
{
   
       $fetch_name="select name from mg_sales_flat_order_item where item_id='".$_GET["detl"]."'";
	   $name= $connection->fetchOne($fetch_name);
	   
	    $name=str_replace("'","",$name);
	   
	   $fetch_qty_ordered="select qty_ordered from mg_sales_flat_order_item where item_id='".$_GET["detl"]."'";
	   $qty_ordered= $connection->fetchOne($fetch_qty_ordered);
	   
	   $fetch_price="select price from mg_sales_flat_order_item where item_id='".$_GET["detl"]."'";
	   $price= $connection->fetchOne($fetch_price);
	   
	   $operation="Removed ".$name.",Qty Orderd :- ".$qty_ordered.",Price :-".$price ;
	   
	   $insert="insert into orderoperation set oid='".$_GET["oid"]."',pro_id='".$_GET["detl"]."',operation='".$operation."'";
	   $connection->query($insert); 
	   
	   $delete="delete from mg_sales_flat_order_item where item_id='".$_GET["detl"]."'";
	   $connection->query($delete); 
	  
        $currentUrl = Mage::helper('core/url')->getCurrentUrl();
		$currentUrl2 = explode("?",$currentUrl);
		$currentUrl22 = $currentUrl2."?oid=".$_GET['oid'];
	   
	    header("Location:".$currentUrl22);
		
}


if(isset($_GET["qty_set"]))
{
   if($_GET["qty_set"]>=1)
   {
       $nowprice=round(($_GET["qty_set"]*$_GET["proprice"]),4);
    $update="update mg_sales_flat_order_item set qty_invoiced='".$_GET["qty_set"]."',qty_ordered='".$_GET["qty_set"]."',qty_shipped='".$_GET["qty_set"]."',row_total='".$nowprice."',base_row_total='".$nowprice."',row_invoiced='".$nowprice."',base_row_invoiced='".$nowprice."' where item_id='".$_GET["item_id"]."'";
	 $connection->query($update);
	   
	   $fetch_name="select name from mg_sales_flat_order_item where item_id='".$_GET["item_id"]."'";
	   $name= $connection->fetchOne($fetch_name);
	   
	    $name=str_replace("'","",$name);
		
	   $operation="Qty updated for ".$name.",Qty Changed from ".$_GET["qty_orderd"]." to ".$_GET["qty_set"];
	   $insert="insert into orderoperation set oid='".$_GET["oid"]."',pro_id='".$_GET["pro_id"]."',operation='".$operation."'";
	  $connection->query($insert); 
	   
	    $currentUrl = Mage::helper('core/url')->getCurrentUrl();
		$currentUrl2 = explode("?",$currentUrl);
		$currentUrl22 = $currentUrl2."?oid=".$_GET['oid'];
	   
	    header("Location:".$currentUrl22);
	   
   }
}

if(isset($_GET["pciker"]) && $_GET["pciker"]!="")
{ 
?>
<div style="border-bottom:3px solid #dfdfdf;margin-bottom:5px;" >
<?php 
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url77 = explode("?pciker=",$currentUrl);
?>
<a href="<?php echo $url77[0]; ?>" > Back to Delivery Calendar </a>
<br/>
<h3 class="icon-head head-manage-blog" style="padding-left:0px;color:#eb5e00;">Pick Lists of <?php echo $_GET["ode"]; ?> for <?php echo $_GET["pciker"]; ?></h3>
</div>
<br/>
<style>
	.page
	{
	   width:90%;
	}
	td, th 
	{
	   padding-top:5px !important;
	   padding-left:5px !important;
	   padding-right:5px !important;
	   padding-bottom:5px !important;
	   font-size:11px;
	}
	table
	{
	   border-collapse:collapse;
	}
	</style>
   <script type="text/javascript">
		function divprint24()
		{
            var divContents = jQuery("#o1").html();
            var printWindow = window.open('', '', 'height=400,width=800');
            printWindow.document.write('<html><head><title> Pick List </title>');
            printWindow.document.write('</head><body >');
            printWindow.document.write(divContents);
            printWindow.document.write('</body></html>');
            printWindow.document.close();
            printWindow.print();
        }
    </script>
    <a href="javascript:void(0);" onClick="divprint24();"> Print </a> 
    <br/>
	<div id="o1">
	<?php  
	$sql3e = "SELECT mei.value,msi.product_id,msi.qty_ordered as qotd,msi.name,msi.sku,msi.`order_id`,mop.picker_id,rr.value as val,rr2.value as sval,rr3.value as tval,rr4.value as uval,mcv.value as fname,mcv2.value as lname,rr2.store_id,
    ( CASE rr2.value 
	WHEN 'Produce' THEN 1
	WHEN '1' THEN 2
	WHEN '2' THEN 3
	WHEN '3' THEN 4
	WHEN '4' THEN 5
	WHEN '5' THEN 6
	WHEN '6' THEN 7
	WHEN '7' THEN 8
	WHEN '8' THEN 9
	WHEN '9' THEN 10
	WHEN 'Bakery' THEN 11
	WHEN 'Deli' THEN 12
	WHEN 'F' THEN 13
	WHEN 'R' THEN 14
	ELSE 15
	END ) as abc FROM `mg_sales_flat_order_item` msi
						left join mg_sales_flat_order_grid mog on msi.`order_id` = mog.`entity_id`
						left join mg_shipping_delivery_window msw on mog.`increment_id` = msw.`order_number`
						left join mg_order_picker mop on mog.`increment_id` = mop.`order_number`
						left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251 and mei.store_id = 0
						left join mg_catalog_product_entity_int rr on msi.product_id = rr.entity_id and rr.attribute_id =  252 and rr.store_id = 0
						left join mg_catalog_product_entity_int qrr on msi.product_id = qrr.entity_id and qrr.attribute_id =  253 and rr.store_id = 0
						left join mg_eav_attribute_option_value rr2 on rr.value = rr2.option_id and rr2.store_id = 0
						left join mg_eav_attribute_option_value rr3 on mei.value = rr3.option_id and rr3.store_id = 0
						left join mg_eav_attribute_option_value rr4 on qrr.value = rr4.option_id and rr4.store_id = 0
						left join mg_customer_entity_varchar mcv on mog.customer_id = mcv.entity_id and mcv.attribute_id = 5
						left join mg_customer_entity_varchar mcv2 on mog.customer_id = mcv2.entity_id and mcv2.attribute_id = 7
						where msw.`window` LIKE '%".$_GET["ode"]."' and mop.picker_id='".$_GET["pciker"]."' and ( mei.value=143 ) and mog.customer_id is not NULL order by abc,rr3.value,rr4.value" ;
	?>
	 <table border=1 cellpadding="5" cellspacing="5" style="border-collapse:collapse;margin-top:10px;font-size:11px;"  >
				  <tr><td colspan=6><b>Product Type : Dry</b></td></tr>
				  <tr>
                   <th style="text-align:left;width:430px;" >Product Name</th>				  
				   <th style="text-align:left;width:25px;">Qty</th> <th style="text-align:left;width:225px;">Customer Name</th>
				   </tr> 
                   <?php   
                    $rows3e = $connection->fetchAll($sql3e); 
	                $green = 0;			
	                $bpil = 0;	
					$kbr="";
					foreach ($rows3e as $value3e) {
					if($value3e["sval"]!=$kbr)
					{
					   echo "<tr><td colspan='3' style='text-align:center;font-weight:bold;'> Location : ".$value3e["sval"]."</td></tr>";
					}
					$kbr = $value3e["sval"];
					$bpil = $bpil + $value3e["qotd"];
					$green = $green + 1;
					$qrt = explode(".",$value3e["qotd"]);
?>                  <tr <?php if($qrt["0"]==2) { ?> style="background:#e0e0e0;font-weight:bold;" <?php } ?> <?php if($qrt["0"]>=3) { ?> style="background:#e0e0e0;font-weight:bold;font-style:italic;" <?php } ?> >
					<td style="width:430px;"><?php echo $value3e["name"]; ?></td>
					<td style="width:25px;"><?php echo $qrt["0"]; ?></td><td style="width:225px;"><?php echo $value3e["fname"]; ?> <?php echo $value3e["lname"]; ?></td>
					</tr>
               <?php					
					}	
                ?>
</table>
    <?php  
  $sql3e = "SELECT mei.value,msi.product_id,msi.qty_ordered as qotd,msi.qty_ordered as qotd,msi.name,msi.sku,msi.`order_id`,mop.picker_id,rr.value as val,rr2.value as sval,rr3.value as tval,rr4.value as uval,mcv.value as fname,mcv2.value as lname,rr2.store_id,
    ( CASE rr2.value 
	WHEN 'Produce' THEN 1
	WHEN 'Dairy' THEN 2
	WHEN 'Packed Meat' THEN 3
	WHEN 'Cut Meat' THEN 4
	WHEN 'Seafood' THEN 5
	WHEN 'Bakery' THEN 6
	WHEN 'Deli' THEN 7
	ELSE 8
	END ) as abc
    FROM `mg_sales_flat_order_item` msi
					
					left join mg_sales_flat_order_grid mog on msi.`order_id` = mog.`entity_id`
					left join mg_shipping_delivery_window msw on mog.`increment_id` = msw.`order_number`
					left join mg_order_picker mop on mog.`increment_id` = mop.`order_number`
					left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251 and mei.store_id = 0
					left join mg_catalog_product_entity_int rr on msi.product_id = rr.entity_id and rr.attribute_id =  252 and rr.store_id = 0
					left join mg_catalog_product_entity_int qrr on msi.product_id = qrr.entity_id and qrr.attribute_id =  253 and rr.store_id = 0
					left join mg_eav_attribute_option_value rr2 on rr.value = rr2.option_id and rr2.store_id = 0
					left join mg_eav_attribute_option_value rr3 on mei.value = rr3.option_id and rr3.store_id = 0
					left join mg_eav_attribute_option_value rr4 on qrr.value = rr4.option_id and rr4.store_id = 0
					left join mg_customer_entity_varchar mcv on mog.customer_id = mcv.entity_id and mcv.attribute_id = 5
					left join mg_customer_entity_varchar mcv2 on mog.customer_id = mcv2.entity_id and mcv2.attribute_id = 7
					where msw.`window` LIKE '%".$_GET["ode"]."' and mop.picker_id='".$_GET["pciker"]."' and ( mei.value=140 ) and mog.customer_id is not NULL order by abc,sval,rr4.value";
?>
	<table border=1 cellpadding="5" cellspacing="5" style="border-collapse:collapse;margin-top:10px;page-break-before:always;font-size:11px;" >
				   <tr><td colspan=6><b>Product Type : Cold</b></td></tr>
				   <tr>
                   <th style="text-align:left;width:430px;" >Product Name</th>				  
				   <th style="text-align:left;width:25px;">Qty</th> <th style="text-align:left;width:225px;">Customer Name</th>
				   </tr> 
<?php   
    $rows3e = $connection->fetchAll($sql3e); 
	$green = 0;	
	$kbr = "";			
					foreach ($rows3e as $value3e) {
					
					if($value3e["sval"]!=$kbr)
					{
					   echo "<tr><td colspan='3' style='text-align:center;font-weight:bold;'> Location  :".$value3e["sval"]."</td></tr>";
					}
					
					$kbr = $value3e["sval"];
					
					$bpil = $bpil + $value3e["qotd"];
					$green = $green + 1;
					$qrt = explode(".",$value3e["qotd"]);
?>      <tr <?php if($qrt["0"]==2) { ?> style="background:#e0e0e0;font-weight:bold;" <?php } ?> <?php if($qrt["0"]>=3) { ?> style="background:#e0e0e0;font-weight:bold;font-style:italic;" <?php } ?> >
					<td style="width:430px;"><?php echo $value3e["name"]; ?></td>
					<td style="width:25px;"><?php echo $qrt["0"]; ?></td><td style="width:225px;"><?php echo $value3e["fname"]; ?> <?php echo $value3e["lname"]; ?></td>
					</tr>
<?php					
	}	
?>
<!-- <tr><td colspan="6" align="right">Total = <?php echo $bpil; ?> </td></tr> -->
 </table> 
		<?php  
		   
		   
		   $sql3e = "SELECT mei.value,msi.product_id,msi.qty_ordered as qotd,msi.name,msi.sku,msi.`order_id`,mop.picker_id,rr.value as val,rr2.value as sval,rr3.value as tval,rr4.value as uval,mcv.value as fname,mcv2.value as lname,rr2.store_id,
    ( CASE rr2.value 
	WHEN '8' THEN 1
	WHEN '9' THEN 2
	WHEN 'Seafood' THEN 3
	WHEN 'Packed Meat' THEN 4
	WHEN 'Cut Meat' THEN 5
	WHEN 'Dairy' THEN 6
	ELSE 7
	END ) as abc FROM `mg_sales_flat_order_item` msi
							
							left join mg_sales_flat_order_grid mog on msi.`order_id` = mog.`entity_id`
							left join mg_shipping_delivery_window msw on mog.`increment_id` = msw.`order_number`
							left join mg_order_picker mop on mog.`increment_id` = mop.`order_number`
							left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251 and mei.store_id = 0
							left join mg_catalog_product_entity_int rr on msi.product_id = rr.entity_id and rr.attribute_id =  252 and rr.store_id = 0
							left join mg_catalog_product_entity_int qrr on msi.product_id = qrr.entity_id and qrr.attribute_id =  253 and rr.store_id = 0
							left join mg_eav_attribute_option_value rr2 on rr.value = rr2.option_id and rr2.store_id = 0
							left join mg_eav_attribute_option_value rr3 on mei.value = rr3.option_id and rr3.store_id = 0
							left join mg_eav_attribute_option_value rr4 on qrr.value = rr4.option_id and rr4.store_id = 0
							left join mg_customer_entity_varchar mcv on mog.customer_id = mcv.entity_id and mcv.attribute_id = 5
							left join mg_customer_entity_varchar mcv2 on mog.customer_id = mcv2.entity_id and mcv2.attribute_id = 7
							where msw.`window` LIKE '%".$_GET["ode"]."' and mop.picker_id='".$_GET["pciker"]."' and ( mei.value=142 ) and mog.customer_id is not NULL order by abc,rr3.value ,rr2.value";
							
		  
		?>
	<table border=1 cellpadding="5" cellspacing="5" style="border-collapse:collapse;margin-top:10px;page-break-before:always;font-size:11px;" >
				  <tr <?php if($qrt["0"]==2) { ?> style="background:#e0e0e0;font-weight:bold;" <?php } ?> <?php if($qrt["0"]>=3) { ?> style="background:#e0e0e0;font-weight:bold;font-style:italic;" <?php } ?> ><td colspan=6><b>Product Type : Frozen</b></td></tr>
				   <tr>
                   <th style="text-align:left;width:430px;" >Product Name</th>				  
				   <th style="text-align:left;width:25px;">Qty</th> <th style="text-align:left;width:225px;">Customer Name</th>
				   </tr> 
<?php   
    $rows3e = $connection->fetchAll($sql3e); 
	$green = 0;	
	$bpil = 0;		
	$kbr = "";	
					foreach ($rows3e as $value3e) {
					$bpil = $bpil + $value3e["qotd"];
					 $green = $green + 1;
					 $qrt = explode(".",$value3e["qotd"]);
					 if($value3e["sval"]!=$kbr)
					{
					   echo "<tr><td colspan='3' style='text-align:center;font-weight:bold;'> Location : ".$value3e["sval"]."</td></tr>";
					}
					$kbr = $value3e["sval"];
?>
                    <tr <?php if($qrt["0"]==2) { ?> style="background:#e0e0e0;font-weight:bold;" <?php } ?> <?php if($qrt["0"]>=3) { ?> style="background:#e0e0e0;font-weight:bold;" <?php } ?> >
					<td style="width:430px;"><?php echo $value3e["name"]; ?></td>
					<td style="width:25px;"><?php echo $qrt["0"]; ?></td><td style="width:225px;"><?php echo $value3e["fname"]; ?> <?php echo $value3e["lname"]; ?></td>
					</tr>
               <?php					
					}	
                 ?>
</table>
</div>
<br/>
<h3 class="icon-head head-manage-blog" style="padding-left:0px;color:#eb5e00;">Packing Lists of <?php echo $_GET["ode"]; ?> for <?php echo $_GET["pciker"]; ?></h3>
<script type="text/javascript">
		function divprint242()
		{
            var divContents = jQuery("#o12").html();
            var printWindow = window.open('', '', 'height=400,width=800');
            printWindow.document.write('<html><head><title> Pick List </title>');
            printWindow.document.write('</head><body >');
            printWindow.document.write(divContents);
            printWindow.document.write('</body></html>');
            printWindow.document.close();
            printWindow.print();
        }
		
		function divprint2425()
		{
            var divContents = jQuery("#o124").html();
            var printWindow = window.open('', '', 'height=400,width=800');
            printWindow.document.write('<html><head><title> Pick List </title>');
            printWindow.document.write('</head><body >');
            printWindow.document.write(divContents);
            printWindow.document.write('</body></html>');
            printWindow.document.close();
            printWindow.print();
        }
    </script>
    <a href="javascript:void(0);" onClick="divprint242();"> Print Dry/Cold/Frozen ListList </a> &nbsp;&nbsp; 
    <br/>
	<div id="o12">
<?php  
                    $sql3eb = "SELECT mog.customer_id,mcv.value as fname,mcv2.value as lname FROM `mg_sales_flat_order_item` msi
					left join mg_sales_flat_order_grid mog on msi.`order_id` = mog.`entity_id`
					left join mg_shipping_delivery_window msw on mog.`increment_id` = msw.`order_number`
					left join mg_order_picker mop on mog.`increment_id` = mop.`order_number`
					left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251 and mei.store_id = 0
					left join mg_catalog_product_entity_int rr on msi.product_id = rr.entity_id and rr.attribute_id =  252 and rr.store_id = 0
					left join mg_catalog_product_entity_int qrr on msi.product_id = qrr.entity_id and qrr.attribute_id =  253 and rr.store_id = 0
					left join mg_eav_attribute_option_value rr2 on rr.value = rr2.option_id and rr2.store_id = 0
					left join mg_eav_attribute_option_value rr3 on mei.value = rr3.option_id and rr3.store_id = 0
					left join mg_eav_attribute_option_value rr4 on qrr.value = rr4.option_id and rr4.store_id = 0
					left join mg_customer_entity_varchar mcv on mog.customer_id = mcv.entity_id and mcv.attribute_id = 5
					left join mg_customer_entity_varchar mcv2 on mog.customer_id = mcv2.entity_id and mcv2.attribute_id = 7
					where msw.`window` LIKE '%".$_GET["ode"]."' and mop.picker_id='".$_GET["pciker"]."' and ( mei.value=141 or mei.value=143 ) and mog.customer_id is not NULL group by mog.customer_id";
					  $rows3ek = $connection->fetchAll($sql3eb); 
	                  $green2 = 0;		
					foreach ($rows3ek as $value3ek) {
					 $bpil = 0;	
   $sql3e = "SELECT mei.value,msi.product_id,msi.qty_ordered as qotd,msi.qty_ordered as qotd,msi.name,msi.sku,msi.`order_id`,mop.picker_id,rr.value as val,rr2.value as sval,rr3.value as tval,rr4.value as uval,mcv.value as fname,mcv2.value as lname FROM `mg_sales_flat_order_item` msi
					left join mg_sales_flat_order_grid mog on msi.`order_id` = mog.`entity_id`
					left join mg_shipping_delivery_window msw on mog.`increment_id` = msw.`order_number`
					left join mg_order_picker mop on mog.`increment_id` = mop.`order_number`
					left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251 and mei.store_id = 0
					left join mg_catalog_product_entity_int rr on msi.product_id = rr.entity_id and rr.attribute_id =  252 and rr.store_id = 0
					left join mg_catalog_product_entity_int qrr on msi.product_id = qrr.entity_id and qrr.attribute_id =  253 and rr.store_id = 0
					left join mg_eav_attribute_option_value rr2 on rr.value = rr2.option_id and rr2.store_id = 0
					left join mg_eav_attribute_option_value rr3 on mei.value = rr3.option_id and rr3.store_id = 0
					left join mg_eav_attribute_option_value rr4 on qrr.value = rr4.option_id and rr4.store_id = 0
					left join mg_customer_entity_varchar mcv on mog.customer_id = mcv.entity_id and mcv.attribute_id = 5
					left join mg_customer_entity_varchar mcv2 on mog.customer_id = mcv2.entity_id and mcv2.attribute_id = 7
					where msw.`window` LIKE '%".$_GET["ode"]."' and mop.picker_id='".$_GET["pciker"]."' and ( mei.value=141 or mei.value=143 ) and mog.customer_id = '".$value3ek["customer_id"]."' order by rr3.value,rr2.value desc,rr4.value desc,msi.name";
					
  
?>

   <br/>
	<table border=1 cellpadding="5" cellspacing="5" style="border-collapse:collapse;<?php if($green2>0) { echo 'page-break-before: always;'; } ?>" >
				   <tr><td colspan=3 align="center"><b>Dry List</b> <b> for customer <?php echo $value3ek["fname"]; ?> <?php echo $value3ek["lname"]; ?></b></td></tr>
				   <tr>
				   <th style="text-align:left;width:600px;text-align:left;" >Product Name</th>
				   <th style="text-align:left;width:100px;">Qty</th>
				   </tr> 
<?php   
   	
   
   $rows3e = $connection->fetchAll($sql3e); 
	                $kbr = "";	
					foreach ($rows3e as $value3e) {
					 $bpil = $bpil + $value3e["qotd"];
					 $green = $green + 1;
					 $qrt = explode(".",$value3e["qotd"]);
					 
					 if($value3e["sval"]!=$kbr)
					{
					   echo "<tr><td colspan='3' style='text-align:center;font-weight:bold;'> Location : ".$value3e["sval"]."</td></tr>";
					   
					}
					
					$kbr = $value3e["sval"];
?>


                    <tr <?php if($qrt["0"]==2) { ?> style="background:#e0e0e0;font-weight:bold;" <?php } ?> <?php if($qrt["0"]>=3) { ?> style="background:#e0e0e0;font-weight:bold;font-style:italic;" <?php } ?> >
					<td><?php echo $value3e["name"]; ?></td>
					<!-- <td><?php echo $value3e["tval"]; ?></td>
					<td><?php echo $green; ?></td>
					
					
					<td><?php echo $value3e["sval"]; ?></td>
					<td><?php echo $value3e["uval"]; ?></td>
					<td><?php echo $value3e["fname"]; ?> <?php echo $value3e["lname"]; ?></td> -->
					<td><?php echo $qrt["0"]; ?></td>
					
					</tr>
					

<?php					
					}	
?>

<tr><td colspan="3" align="right">Total = <?php echo $bpil; ?> </td></tr>

</table>

<?php 

$green2 = $green2 + 1 ; } ?>


           <?php  
                    $sql3eb = "SELECT mog.customer_id,mcv.value as fname,mcv2.value as lname FROM `mg_sales_flat_order_item` msi
					left join mg_sales_flat_order_grid mog on msi.`order_id` = mog.`entity_id`
					left join mg_shipping_delivery_window msw on mog.`increment_id` = msw.`order_number`
					left join mg_order_picker mop on mog.`increment_id` = mop.`order_number`
					left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251 and mei.store_id = 0
					left join mg_catalog_product_entity_int rr on msi.product_id = rr.entity_id and rr.attribute_id =  252 and rr.store_id = 0
					left join mg_catalog_product_entity_int qrr on msi.product_id = qrr.entity_id and qrr.attribute_id =  253 and rr.store_id = 0
					left join mg_eav_attribute_option_value rr2 on rr.value = rr2.option_id and rr2.store_id = 0
					left join mg_eav_attribute_option_value rr3 on mei.value = rr3.option_id and rr3.store_id = 0
					left join mg_eav_attribute_option_value rr4 on qrr.value = rr4.option_id and rr4.store_id = 0
					left join mg_customer_entity_varchar mcv on mog.customer_id = mcv.entity_id and mcv.attribute_id = 5
					left join mg_customer_entity_varchar mcv2 on mog.customer_id = mcv2.entity_id and mcv2.attribute_id = 7
					where msw.`window` LIKE '%".$_GET["ode"]."' and mop.picker_id='".$_GET["pciker"]."' and ( mei.value=140 or mei.value=142 or mei.value=144 or mei.value=145 or mei.value=146 ) and mog.customer_id is not NULL group by mog.customer_id";
					$rows3ek = $connection->fetchAll($sql3eb); 
	                $green2 = 0;				
					foreach ($rows3ek as $value3ek) {
					 $bpil = 0;	
   $sql3e = "SELECT mei.value,msi.product_id,msi.item_id,msi.qty_ordered as qotd,msi.qty_ordered as qotd,msi.name,msi.sku,msi.`order_id`,mop.picker_id,rr.value as val,rr2.value as sval,rr3.value as tval,rr4.value as uval,mcv.value as fname,mcv2.value as lname FROM `mg_sales_flat_order_item` msi
					
					left join mg_sales_flat_order_grid mog on msi.`order_id` = mog.`entity_id`
					left join mg_shipping_delivery_window msw on mog.`increment_id` = msw.`order_number`
					left join mg_order_picker mop on mog.`increment_id` = mop.`order_number`
					left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251 and mei.store_id = 0
					left join mg_catalog_product_entity_int rr on msi.product_id = rr.entity_id and rr.attribute_id =  252 and rr.store_id = 0
					left join mg_catalog_product_entity_int qrr on msi.product_id = qrr.entity_id and qrr.attribute_id =  253 and rr.store_id = 0
					left join mg_eav_attribute_option_value rr2 on rr.value = rr2.option_id and rr2.store_id = 0
					left join mg_eav_attribute_option_value rr3 on mei.value = rr3.option_id and rr3.store_id = 0
					left join mg_eav_attribute_option_value rr4 on qrr.value = rr4.option_id and rr4.store_id = 0
					left join mg_customer_entity_varchar mcv on mog.customer_id = mcv.entity_id and mcv.attribute_id = 5
					left join mg_customer_entity_varchar mcv2 on mog.customer_id = mcv2.entity_id and mcv2.attribute_id = 7
					where msw.`window` LIKE '%".$_GET["ode"]."' and mop.picker_id='".$_GET["pciker"]."' and ( mei.value=140 or mei.value=142 or mei.value=144 or mei.value=145 or mei.value=146 ) and mog.customer_id = '".$value3ek["customer_id"]."' order by rr3.value,rr2.value desc,rr4.value desc,msi.name";
					
  
?>

   <br/>
	<table border=1 cellpadding="5" cellspacing="5" style="font-size:11px;border-collapse:collapse;<?php if($green2>=0) { echo 'page-break-before: always;'; } ?>" >
				  
				   <tr><td colspan=3 align="center"><b>Cold/Frozen List</b> <b> for customer <?php echo $value3ek["fname"]; ?> <?php echo $value3ek["lname"]; ?></b></td></tr>
				   
				   <tr>
				   <th style="text-align:left;width:600px;text-align:left;" >Product Name</th>
				   <th style="text-align:left;width:100px;">Qty</th>
				   </tr> 
<?php   
                    $rows3e = $connection->fetchAll($sql3e); 
					foreach ($rows3e as $value3e) {
					 $bpil = $bpil + $value3e["qotd"];
					 $green = $green + 1;
					 $qrt = explode(".",$value3e["qotd"]);
?>
                    <tr <?php if($qrt["0"]==2) { ?> style="background:#e0e0e0;font-weight:bold;" <?php } ?> <?php if($qrt["0"]>=3) { ?> style="background:#e0e0e0;font-weight:bold;font-style:italic;" <?php } ?> >
					<td><?php echo $value3e["name"]; ?></td>
					<td><?php echo $qrt["0"]; ?></td>
					</tr>
<?php					
	}	
?>

<tr><td colspan="3" align="right">Total = <?php echo $bpil; ?> </td></tr>

</table>

<?php 

$green2 = $green2 + 1 ; } ?>

</div>

 <!-- <div>
<table border=1 cellpadding="5" cellspacing="5" style="border-collapse:collapse;font-size:11px;" >
 <tr><td colspan=7><b>Cold/Frozen List</b></td></tr>

<?php  
   
   
   $sql3e = "SELECT mei.value,msi.product_id,msi.qty_ordered as qotd,msi.qty_ordered as qotd,msi.name,msi.sku,msi.`order_id`,mop.picker_id,rr.value as val,rr2.value as sval,rr3.value as tval,rr4.value as uval,mcv.value as fname,mcv2.value as lname FROM `mg_sales_flat_order_item` msi
					
					left join mg_sales_flat_order_grid mog on msi.`order_id` = mog.`entity_id`
					left join mg_shipping_delivery_window msw on mog.`increment_id` = msw.`order_number`
					left join mg_order_picker mop on mog.`increment_id` = mop.`order_number`
					left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251 and mei.store_id = 0
					left join mg_catalog_product_entity_int rr on msi.product_id = rr.entity_id and rr.attribute_id =  252 and rr.store_id = 0
					left join mg_catalog_product_entity_int qrr on msi.product_id = qrr.entity_id and qrr.attribute_id =  253 and rr.store_id = 0
					left join mg_eav_attribute_option_value rr2 on rr.value = rr2.option_id and rr2.store_id = 0
					left join mg_eav_attribute_option_value rr3 on mei.value = rr3.option_id and rr3.store_id = 0
					left join mg_eav_attribute_option_value rr4 on qrr.value = rr4.option_id and rr4.store_id = 0
					left join mg_customer_entity_varchar mcv on mog.customer_id = mcv.entity_id and mcv.attribute_id = 5
					left join mg_customer_entity_varchar mcv2 on mog.customer_id = mcv2.entity_id and mcv2.attribute_id = 7
					where msw.`window` LIKE '%".$_GET["ode"]."' and mop.picker_id='".$_GET["pciker"]."' and ( mei.value=140 or mei.value=142 or mei.value=144 or mei.value=145 or mei.value=146 ) and mog.customer_id is not NULL order by rr3.value,rr2.value,rr4.value desc ";
    $rows3e = $connection->fetchAll($sql3e); 
	$green = 0;				
	$bpil = 0;
					foreach ($rows3e as $value3e) {
					 $bpil = $bpil + $value3e["qotd"];
					 $green = $green + 1;
					 $qrt = explode(".",$value3e["qotd"]);
?>                  <tr>
					<td><?php echo $green; ?></td>
					<td><?php echo $value3e["name"]; ?></td>
					<td><?php echo $value3e["tval"]; ?></td>
					<td><?php echo $value3e["sval"]; ?></td>
					<td><?php echo $value3e["uval"]; ?></td>
					<td><?php echo $value3e["fname"]; ?> <?php echo $value3e["lname"]; ?></td>
					<td><?php echo $qrt["0"]; ?></td>
					</tr>
                   <?php					
					}	
                    ?>
                    <tr><td colspan="7" align="right">Total = <?php echo $bpil; ?> </td></tr>
 </table> 
</div>  -->
<?php																	
}
else
{
if(isset($_GET) &&  $_GET["oid"]=="" )
{
	while (list($key, $val) = each($_GET)) {
	   if($key!="")
	   {
	   
	           $sql22k = "SELECT order_id FROM mg_order_picker where `ordertext`='".$key."'";
		       $rows22k = $connection->fetchOne($sql22k);
			   
			   if($rows22k=="")
			   {
			       $tt=explode("-",$key);
				   
				   $sql555556 = "SELECT `window` FROM `mg_shipping_delivery_window` where `order_number`='".$tt[1]."'";
			       $rows555556 = $connection->fetchOne($sql555556);
			   
			       $sql3w  = "SELECT SUM(qty_ordered) FROM `mg_sales_flat_order_item` where `order_id`='".$tt[0]."'";
			       $rows3w = $connection->fetchOne($sql3w); 
				 
				 if($tt[0]>=1)
				 {
			       $insert="insert into mg_order_picker set `ordertext`='".$key."',order_id='".$tt[0]."',order_number='".$tt[1]."',picker_id='".$val."',window='".date("d_m_Y")."',items='".$rows3w."'";
				    $connection->query($insert);
				 }
			   }
			   else
			   {
			       $tt=explode("-",$key);
				   $sql3w  = "SELECT SUM(qty_ordered) FROM `mg_sales_flat_order_item` where `order_id`='".$tt[0]."'";
			       $rows3w = $connection->fetchOne($sql3w); 
				   
				   if($tt[0]>=1)
				 {
			       $update="update mg_order_picker set picker_id='".$val."',items='".$rows3w."',window='".date("d_m_Y")."' where `order_id`='".$tt[0]."'";
				   $connection->query($update);
				  } 
				   
			   }
	   }
	
     }
?>
<script type="text/javascript">

	jQuery(document).ready(function(){
	<?php if(isset($_GET["trid"])) { ?>
	gotodive();
	<?php } ?>
	});
	
function gotodive()
{
	document.getElementById('green').scrollIntoView();
}					
</script>
<?php	 
}
?>
<?php if(isset($_GET["oid"]) && $_GET["oid"]!="" ) {
    
     $order = Mage::getModel('sales/order')->load($_GET["oid"], 'increment_id');
	 $order->getAllVisibleItems();
	 $address = $order->getShippingAddress();
	 $address2 = $order->getBillingAddress();
	 $orderValue = $order->getSubtotal();
	 $orderValue2 = $order->getBaseGrandTotal();
?>	 

<style>
.page
{
   width:90%;
}
td, th 
{
   padding:5px !important;
   font-size:12px;
   color:#000;
}
table
{
   border-color:#000;
}
th 
{
   color:#000;
}
</style>
<div style="border-bottom:3px solid #dfdfdf;margin-bottom:5px;" >
<h3 class="icon-head head-manage-blog" style="padding-left:0px;color:#eb5e00;">Order Details ( <?php echo $_GET["oid"]; ?> )</h3>
<?php 
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url77 = explode("?oid=",$currentUrl);

?>

<a href="<?php echo $url77[0]; ?>" > Back to Delivery Calendar </a>

</div>
	 <b> Delivery Address :- </b>   
	             <?php echo $custName = $address->getName()."&nbsp;&nbsp;";
				echo $custAddr = $address->getStreetFull()."&nbsp;&nbsp;";
				echo $region2 = $address->getCity()."&nbsp;&nbsp;";
				echo $region = $address->getRegion()."&nbsp;&nbsp;";
				echo $country = $address["postcode"]; ?>	
				
	 <br/><br/><b> Billing Address :- </b>   	
	  <?php echo $custName = $address2->getName()."&nbsp;&nbsp;";
				echo $custAddr = $address2->getStreetFull()."&nbsp;&nbsp;";
				echo $region2 = $address2->getCity()."&nbsp;&nbsp;";
				echo $region = $address2->getRegion()."&nbsp;&nbsp;";
				echo $country = $address2["postcode"]; ?>
		<br/><br/>
		<b> Customer :- </b> 
		<?php echo $custName; ?>		
		&nbsp; &nbsp;	
		
		
		<b> Customer Telephone :- </b> 
		<?php echo $address->getTelephone(); ?>		
		&nbsp; &nbsp;	
		<br/><br/>
		
			
	  <?php
	  		$sql55555 = "SELECT `window` FROM `mg_shipping_delivery_window` where `order_number`='".$_GET["oid"]."'";
			$rows55555 = $connection->fetchOne($sql55555);
			 $temp = explode("|",$rows55555);
		 ?>	 
		 
		 <b> Delivery Date :- </b>
		<?php if($temp[1]=="") { echo $temp[0]; } else { echo $temp[1]; } ?>
		&nbsp; &nbsp;<b> Delivery Time :- </b> 
			 <?php if($temp[1]=="") { echo 'Flexible Time'; } else { echo $temp[0]; } ?>
		 	
<?php 
   $value["order_number"] = $_GET["oid"];
   if($value["order_number"]!="")
		   {
		       $sql2        = "SELECT entity_id FROM mg_sales_flat_order_grid where increment_id='".$value["order_number"]."'";
		       $rows2 = $connection->fetchOne($sql2);
			   echo "<br/>";
			  
				$sql3        = "SELECT mei.value,msi.item_id,msi.product_id,msi.price,msi.row_total,msi.qty_ordered,msi.name,msi.sku FROM `mg_sales_flat_order_item` msi
			    left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251
			    where msi.`order_id`='".$rows2."'";
				
			   $rows3 = $connection->fetchAll($sql3); 
			   
			   
			   
			   $sel_check_operation="select * from orderoperation where oid='".$_GET["oid"]."'";
			   $rows3heck_operation = $connection->fetchAll($sel_check_operation); 
			   
			   
			   
			   if(count($rows3heck_operation>=1))
			   {
			   ?>
			   
			   <table border=1 cellpadding="5" cellspacing="5" border="1" style="border-collapse:collapse;margin-bottom:20px;margin-top:15px;" >
			   
			   <tr style="background:red;color:#fff;">
			   <th> Order Edits </th>
			   </tr>
			   
			   <?php
			   foreach ($rows3heck_operation as $value3) {
			   ?>
			   
			   
			   <tr>
			   <td> <?php echo $value3["operation"]; ?></td>
			   </tr>
			   
			   <?php } ?>
			   
			   </table>
			   
			   <?php
			   }
			   ?>
			   
			   
			   <br/><br/><b> Order Items </b>   	
			   
			   <table border=1 cellpadding="5" cellspacing="5" border="1" style="border-collapse:collapse" >
			   <tr>
			   <th >Product Name</th>
			   <th>Sku</th>
			   <th>Price</th>
			   <th>Qty</th>
			   <th>Subtotal</th>
			   <th>Product Type</th>
			   <th>Change Qty</th>
			   <th>Remove Item</th>
			   </tr>
			   
			   <?php
			   $rr=0;
			   foreach ($rows3 as $value3) {
			   
				$_resource = Mage::getSingleton('catalog/product')->getResource();
				$optionValue1 = $_resource->getAttributeRawValue($value3["product_id"],'protype', Mage::app()->getStore());
				
				$product = Mage::getModel('catalog/product')->setStoreId($store_id)->setProtype($optionValue1);
                $optionLabel1 = $product->getAttributeText('protype');

				$optionValue4 = $_resource->getAttributeRawValue($value3["product_id"],'vendor_product_id', Mage::app()->getStore());
				
				$rr = $rr + $value3["row_total"];
			   ?>
			  
			    <tr>
				<td><?php echo $value3["name"]; ?></td>
				<td><?php echo $value3["sku"]; ?></td>
				<td>$<?php echo number_format($value3["price"], 2, '.', ''); ?></td>
				<td><?php echo round($value3['qty_ordered'],0); ?></td>
				<td>$<?php echo number_format($value3["row_total"], 2, '.', ''); ?></td>
				<td><?php echo $optionLabel1; ?></td>
				<td>  <form method="get" action="" name="editform<?php echo $value3["item_id"]; ?>" id="editform<?php echo $value3["item_id"]; ?>"><input type="text" style="width:20px;" name="qty_set" value="<?php echo round($value3['qty_ordered'],0); ?>" /><br/><button style="margin-top:15px;" onClick="gosubmit(<?php echo $value3["item_id"]; ?>)" class="scalable " type="button" id="id_sxIHHR43YtHVy4TP"><span>Change Qty</span></button><input type="hidden" name="item_id" id="item_id" value="<?php echo $value3["item_id"]; ?>" />
				<input type="hidden" name="qty_orderd" id="qty_orderd" value="<?php echo round($value3["qty_ordered"],0) ?>" />
				<input type="hidden" name="pro_id" id="pro_id" value="<?php echo round($value3["product_id"],0) ?>" />
				<input type="hidden" name="rowtotal" id="rowtotal" value="<?php echo round($value3["row_total"],2) ?>" />
				<input type="hidden" name="proprice" id="proprice" value="<?php echo round($value3["price"],2) ?>" />
				<input type="hidden" name="oid" id="oid" value="<?php echo $_GET["oid"]; ?>" />
			  </form> 
			  
			 <?php
			 
			  $currentUrl = Mage::helper('core/url')->getCurrentUrl();
			  ?>
       			  <td><a href="<?php echo $currentUrl; ?>&detl=<?php echo $value3["item_id"]; ?> " onClick="return confirm('Are you sure you want to remove this item ?');"> Remove Item</a></td>
			  
			   <script type="text/javascript">
       	       function gosubmit(id)
			   {
			      jQuery('#editform'+id).submit();
			   }
</script> </td>
				</tr>
				

			   <?php
			   } 
			   ?>
			   
			  

			   <tr>
			     <td></td>
			   <td style="text-align:right;" colspan="4">
			  
			   <b>
			   <br/>
			    Total : $<?php echo number_format($rr, 2, '.', ''); ?><br/> <br/>
			   Original Subtoal : $<?php echo number_format($orderValue, 2, '.', ''); ?>  <br/>  <br/> 
			   Grandtotal :  $<?php echo number_format($orderValue2, 2, '.', ''); ?>  <br/>
			   </b> 
			   
			  <br/>
			   </td>
			   <td colspan="3" style="background:red;color:#fff;font-size:15px;font-weight:bold;"> Difference Amount : $<?php if($rr!=$orderValue) { echo round($orderValue-$rr,2); } ?></td>
			   </tr>
			    </table>
			   <?php	  
		   }
} else { ?>

<?php
      $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
?>
<style>
body>.wrapper
{
   background:none;
   font-weight:bold;
   color:#fff;
   overflow:hidden;
}
.page
{
   width:90%;
}
td, th 
{
   padding:5px !important;
   font-size:12px;
   color:#000;
}
table
{
   border-color:#000;
}
th 
{
   color:#000;
}
</style>
<div>
<?php
     $kbtnew=date("d_m_Y");
     $sql = "SELECT mw.id FROM `mg_shipping_delivery_window` mw 
	 left join mg_sales_flat_order mo on mw.order_number = mo.increment_id
	 where mw.`window` LIKE '%".$kbtnew."' and mo.status!='canceled'";
	 $rowsss = $connection->fetchAll($sql); 
	 $total_rows = count($rowsss); 
	 
	 
	 $sql = "SELECT mo.entity_id FROM `mg_shipping_delivery_window` mw 
	 left join mg_sales_flat_order mo on mw.order_number = mo.increment_id
	 where mw.`window` LIKE '%".$kbtnew."' and mo.status!='canceled'";
	 $rowsss = $connection->fetchAll($sql); 
	 $trp=0;
	 foreach ($rowsss as $bbbcvv) {
	               $sql3w  = "SELECT SUM(qty_ordered) FROM `mg_sales_flat_order_item` where `order_id`='".$bbbcvv["entity_id"]."'";
			       $rows3w = $connection->fetchOne($sql3w); 
	               $trp=$trp+$rows3w;
	 }
	 
	 for($i=0;$i<=15;$i++){
	   
			 $kbt = (date("d_m_Y",strtotime("+$i days")));
			 $kbt2 = (date("m/d/Y",strtotime("+$i days")));
	 
			 $kbtnew2=$kbt;
			 $sql = "SELECT mw.id FROM `mg_shipping_delivery_window` mw 
			 left join mg_sales_flat_order mo on mw.order_number = mo.increment_id
			 where mw.`window` LIKE '%".$kbtnew2."' and mo.status!='canceled'";
			 $rowsss = $connection->fetchAll($sql); 
			 $total_rows2 = count($rowsss); 
	 
			 $sql = "SELECT mo.entity_id FROM `mg_shipping_delivery_window` mw 
			 left join mg_sales_flat_order mo on mw.order_number = mo.increment_id
			 where mw.`window` LIKE '%".$kbtnew2."' and mo.status!='canceled'";
			 $rowsss = $connection->fetchAll($sql); 
			 $trp2=0;
			 foreach ($rowsss as $bbbcvv) {
			 
						   $sql3w  = "SELECT SUM(qty_ordered) FROM `mg_sales_flat_order_item` where `order_id`='".$bbbcvv["entity_id"]."'";
						   $rows3w = $connection->fetchOne($sql3w); 
						   $trp2=$trp2+$rows3w;
			 }
			 if($total_rows2>=1)
			 {
				$newp[$i] = $total_rows2;
				$newr[$i] = $trp2;
				$news[$i] = $kbt2;
			 } 
  }
?>	  
<h3 class="icon-head head-manage-blog" style="padding-left:0px;color:#eb5e00;">Delivery Calendar ( Today's Order : <?php echo $total_rows; ?> )</h3>
</div>
<div style="color:#000;font-weight:bold;padding-top:10px;padding:10px;width:100%;border:1px solid #000;width:49%;float:left;">
<div style="padding:10px;padding-left:0px;color:#eb5e00;">Select Employees ( Pickers & Supervisor ) </div>
<form name="todaysemp" id="todaysemp" action="" method="GET">
<?php
		$sql444  = "select * from mg_pickers where extra='' and role!='driver' order by name";
	    $rows444 = $connection->fetchAll($sql444);
		$tol=0; 
		$sel_gdates="select emp from toadayemp where dated='".date(d_m_Y)."'";
	    $checkff=$connection->fetchOne($sel_gdates);
	    $tmparray=explode(",",$checkff);
		foreach ($rows444 as $value444) { 
		$tol=$tol+1; ?>
		<input type="checkbox" name="chk-<?php echo $tol; ?>" id="chk-<?php echo $tol; ?>" value="<?php echo $value444["id"]; ?>"
		<?php if (in_array($value444["id"], $tmparray)) { ?> checked <?php } ?>
		 />
		<?php echo $value444["name"]; ?> <br/>
<?php } ?>	
<input type="hidden" name="todl" id="todl" vaule="<?php echo $tol; ?>" />			
<button style="margin-top:15px;" onClick="filterTodaysEmp.submit()" class="scalable " type="button" id="id_<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"><span>Generate</span></button>
</form>
<?php
   $total_packed="select count(item_id) from supervision where  ( realdate >='".date("Y-m-d")."' and realdate <='".date("Y-m-d")."' )";
   $abtotal_packed=$connection->fetchOne($total_packed);
   $greenpack = count($tmparray)-1;
?>		
<script type="text/javascript">
       	 //<![CDATA[
        	var filterTodaysEmp  = new varienForm('todaysemp');
         //]]>
</script> 
</div>
<div style="color:#000;font-weight:bold;padding-top:10px;padding:10px;height:200px;border:1px solid #000;width:45%;float:right;">
     <?php
	 for($i=0;$i<=15;$i++)
	 {
	   if($news[$i]!="")
	   {
	     echo $news[$i]. "&nbsp;&nbsp;&nbsp;<span style='color:green;'> Orders :".$newp[$i]."</span>&nbsp;&nbsp;&nbsp;<span style='color:green;'> Total Items :".$newr[$i]."</span>";
		 if($i==0)
		 {
		 ?>
		 &nbsp;&nbsp;&nbsp;<span style="color:green;">Items / Picker : <?php echo (int) ($trp/$greenpack); ?></span>
		 <?
		 }
		 echo "<br/>";
	   }
	 }
	 
	 $currentUrl4 = Mage::helper('core/url')->getCurrentUrl();
	 
	 if(isset($_GET["gid"]) && $_GET["gid"]=='desc')
	 {
	    $currentUrl42=explode("?",$currentUrl4);
		$currentUrl4 = $currentUrl42[0];
	 }
	 else if(isset($_GET["gid"]))
	 {
	    $currentUrl42=explode("?",$currentUrl4);
		$currentUrl4=$currentUrl42[0]."?gid=desc";
	 }
	 else
	 {
	    $currentUrl42=explode("?",$currentUrl4);
		$currentUrl4=$currentUrl42[0]."?gid=asc";
	 }
	
	 
	 if(isset($_GET["bid"]) && $_GET["bid"]=='desc')
	 {
	    $currentUrl424=explode("?",$currentUrl4);
		$currentUrl44=$currentUrl424[0];
	 }
	 else if(isset($_GET["bid"]))
	 {
	   $currentUrl424=explode("?",$currentUrl4);
	   $currentUrl44=$currentUrl424[0]."?bid=desc";
	 }
	 else
	 {
	    $currentUrl424=explode("?",$currentUrl4);
	    $currentUrl44=$currentUrl424[0]."?bid=asc";
	 }
	 
	 
	    $currentUrl42444=explode("?",$currentUrl4);
	    $currentUrl44uuu=$currentUrl42444[0];
		
	
	 ?>
</div>

<?php
$from_date = date('Y-m-d' . ' 00:00:00');
$sel_gnote="select note from general_note where dodate='".$from_date."'";
$gnote=$connection->fetchOne($sel_gnote);
if($gnote!="")
{
?>

<div style="color:green;font-size:14px;font-weight:bold;clear:both;padding-top:15px;"> General Note :- <?php echo $gnote; ?></div>

<?php } ?>


<form name="frmpick" id="frmpick" action="" method="GET"  >
<table border=1 style="border-collapse:collapse;font-size:11px;">
<tr>
<th style="text-align:left;width:90px;"><b>Delivery Date</b></th>
<th><a href="<?php echo $currentUrl44uuu; ?>"><b>Delivery Time</b></a></th>
<th><b>Order Number</b></th>
<th style="text-align:left;width:160px;"><b>Customer Name</b></th>
<th style="text-align:left;width:420px;"><b>Delivery Address</b> </th>
<th ><a href="<?php echo $currentUrl44; ?>"><b>Picker</b></a> </th>
<th style="text-align:left;width:50px;"><a href="<?php echo $currentUrl4; ?>"><b>Items</b></a></th>
<th style="text-align:left;width:120px;"><b> Assign / Change Picker</b></th>
</tr>
<?php	  
	   $j=0;
	   for($i=0;$i<=15;$i++){
	   
     $kbt = (date("d_m_Y",strtotime("+$i days")));
	 $kbt2 = (date("m-d-Y",strtotime("+$i days")));
	
	if(isset($_GET["gid"]) && $_GET["gid"]=="desc")
	{
		 $sql = "SELECT m.*,SUM(msi.qty_ordered) AS mqo FROM `mg_shipping_delivery_window` m
		 left join mg_sales_flat_order_grid msg on m.order_number=msg.increment_id
		 right join mg_sales_flat_order_item msi on msg.entity_id=msi.order_id
		 where m.`window` LIKE '%".$kbt."' group by msg.increment_id order by mqo DESC";
    }
	else if(isset($_GET["gid"]) && $_GET["gid"]=="asc")
	{
	     $sql = "SELECT m.*,SUM(msi.qty_ordered) AS mqo FROM `mg_shipping_delivery_window` m
		 left join mg_sales_flat_order_grid msg on m.order_number=msg.increment_id
		 right join mg_sales_flat_order_item msi on msg.entity_id=msi.order_id
		 where m.`window` LIKE '%".$kbt."' group by msg.increment_id order by mqo";
	}
	
	else if(isset($_GET["bid"]) && $_GET["bid"]=="desc")
	{
		 $sql = "SELECT m.* FROM `mg_shipping_delivery_window` m
		 left join mg_order_picker mp on mp.order_number=m.order_number
		 left join mg_pickers mpr on mpr.id=mp.picker_id
		 where m.`window` LIKE '%".$kbt."' group by m.order_number order by mpr.name DESC";
    }
	else if(isset($_GET["bid"]) && $_GET["bid"]=="asc")
	{
	     $sql = "SELECT m.* FROM `mg_shipping_delivery_window` m
		 left join mg_order_picker mp on mp.order_number=m.order_number
		 left join mg_pickers mpr on mpr.id=mp.picker_id
		 where m.`window` LIKE '%".$kbt."' group by m.order_number order by mpr.name";
	}
	
	else 
	{
	     $sql = "SELECT m.* FROM `mg_shipping_delivery_window` m
		 where m.`window` LIKE '%".$kbt."' group by m.order_number order by m.window";
	}
	
		 
	 $rows = $connection->fetchAll($sql); 
	 $total_rows = count($rows);
	 
	 if($total_rows>0)
	 {
	    $j=$j+1;
     }
	 
	 if($j%2==0)
	 {
	    $color='#fff';
	 }
	 else
	 {
	    $color='#cecece';
	 }
	  
	  $check=explode("-",$kbt2);
	  $check2[$i] =  $check[1];
	  
	  foreach ($rows as $value) {
	  
	           $sqlstatus = "SELECT status FROM mg_sales_flat_order_grid  where increment_id='".$value["order_number"]."'";
		       $rowstatus = $connection->fetchOne($sqlstatus);
			   
	       if($value["order_number"]!="" && $value["order_number"]!='100003190' && $value["order_number"]!='100007293' && $value["order_number"]!='100007292' && $value["order_number"]!='100005508' && $rowstatus!='canceled' )
		   {
		       $sql2        = "SELECT entity_id FROM mg_sales_flat_order_grid where increment_id='".$value["order_number"]."'";
		       $rows2 = $connection->fetchOne($sql2);
			   
			   $sql22        = "SELECT customer_id FROM mg_sales_flat_order_grid where increment_id='".$value["order_number"]."'";
		       $rows22 = $connection->fetchOne($sql22);
			   
			   $customer = "" ;
			   $customer = Mage::getModel('customer/customer')->load($rows22); 
			   
			   $sql222        = "SELECT entity_id FROM mg_sales_flat_order_grid where customer_id='".$rows22."' and increment_id!='".$value["order_number"]."'";
		       $rows222 = $connection->fetchOne($sql222);
			  
			   $sql3        = "SELECT SUM(qty_ordered) FROM `mg_sales_flat_order_item` where `order_id`='".$rows2."'";
			   $rows3 = $connection->fetchOne($sql3); 
			   $order = Mage::getModel("sales/order")->load($rows2); //load order by order id 
			   $address = $order->getShippingAddress();
			   $temp = explode("|",$value['window']);
			   $temp3 = explode(".",$rows3);
			   $check22 = 0;
			  
			   if($customer->getId()!="120599")
			   {
			  ?>
			
			   <tr style="background-color:<?php echo $color; ?>;" id="tr-<?php echo $rows2; ?>">
			   <td  <?php if($rows222 == "" ) {  echo 'style="color:#0041d7;font-weight:bold;font-size:12px;"'; } ?> ><?php echo $kbt2; ?></td>
			   <td <?php if($rows222 == "" ) {  echo 'style="color:#1c60ff;font-weight:bold;font-size:12px;"'; } ?> ><?php if($temp[1]=="") { echo 'Flexible Time'; } else { echo $temp[0]; } ?></td>
			   <td <?php if($rows222 == "" ) {  echo 'style="color:#1c60ff;font-weight:bold;font-size:12px;"'; } ?>>
			   
			   
			   <a href=""  <?php if($rows222 == "" ) {  echo 'style="color:#1c60ff;font-weight:bold;font-size:12px;text-decoration:underline;"'; } else {  echo 'style="color:#000;font-weight:bold;font-size:12px;text-decoration:underline;"'; } ?> >
			   <?php echo $value['order_number']; ?>
			   </a>
			   
			   <?php $custName = $address->getName(); ?> <?php if(trim($custName)=="") { $rname = $customer->getName(); } else { $rname = $custName; } 
			   $rname3=$rname;
			   $rname33=explode(" ",trim($rname));
			   $max=count($rname33);
			   
			   $new="";
			   for($mm=$max-1;$mm>=0;$mm--)
			   {
			        if($rname33[$mm]!="")
					{
					   $new.=$rname33[$mm];
					}
					
					if($mm>=1)
					{
					   $new.=",";
					}
			   }
			   
			   ?>
			    </td>
			  
			   <td <?php if($rows222 == "" ) {  echo 'style="color:#1c60ff;font-weight:bold;font-size:12px;"'; } ?> ><?php  echo $new; ?> </td>
			   <td <?php if($rows222 == "" ) {  echo 'style="color:#1c60ff;font-weight:bold;font-size:12px;"'; } ?> >
			    <?php
				echo $custAddr = $address->getStreetFull()."&nbsp;&nbsp;";
				echo $region2 = $address->getCity()."&nbsp;&nbsp;";
				echo $region = $address->getRegion()."&nbsp;&nbsp;";
				echo $country = $address["postcode"]; ?>
				</td>
				
				<td>
				<?php $sql2g        = "SELECT picker_id FROM mg_order_picker where order_number='".$value["order_number"]."'";
		        $rows2g = $connection->fetchOne($sql2g);
				
				if($rows2g!="")
			     {
					$currentUrl = Mage::helper('core/url')->getCurrentUrl();
					$url77 = explode("/",$currentUrl);
					
            ?>
                 
				 <a href="http://www.prestofreshgrocery.com/index.php/salesreport/adminhtml_sales/reportmanage/key/<?php echo $url77[8]; ?>/?pciker=<?php echo $rows2g; ?>&ode=<?php echo $kbt; ?>">
				 
				 <?php

				    $sql2gk = "SELECT name FROM mg_pickers where id='".$rows2g."'";
		            echo $rows2gk = $connection->fetchOne($sql2gk);
					
				
				 }
			   ?>
			   </a>
				</td>
				 <td <?php if($rows222 == "" ) {  echo 'style="color:#1c60ff;font-weight:bold;font-size:12px;"'; } ?> ><?php echo $temp3[0]; ?> </td>
				<td>
				<div id="green"></div>
				<input type="hidden" name="trid" id="trid" value="" />
				
				<?php if(isset($_GET["bid"]) && $_GET["bid"]!="" )
				       {
				?>
				<input type="hidden" name="bid" id="bid" value="<?php echo $_GET["bid"]; ?>" />
				<?php } ?>
				
				
				<?php if(isset($_GET["gid"]) && $_GET["gid"]!="" )
				       {
				?>
				<input type="hidden" name="gid" id="gid" value="<?php echo $_GET["gid"]; ?>" />
				<?php } 
			
				?>
				
				
				<select name="<?php echo $rows2; ?>-<?php echo $value['order_number']; ?>-pick" onChange="pickfun(<?php echo $rows2; ?>);">
				<option value=""> None </option>
	 			 <?php
				 $sql444        = "select * from mg_pickers where extra='' order by name";
	             $rows444 = $connection->fetchAll($sql444); 
				 foreach ($rows444 as $value444) {
				 $sqlwr="SELECT SUM(items) FROM mg_order_picker where picker_id='".$value444["id"]."' and window LIKE '%".$kbt."'";
				 $rows3wr = $connection->fetchOne($sqlwr); 
				 if($rows3wr=="")
				 {
				   $rows3wr=0;
				 }
				 ?>
				<?php echo $value444["name"]; ?><?php echo "(".$rows3wr.")"; ?>	
				<?php if (in_array($value444["id"], $tmparray)) { ?>
				<option value="<?php echo $value444["id"]; ?>" <?php if($value444["id"]==$rows2g) { ?> selected <?php } ?> > <?php echo $value444["name"]; ?><?php echo "(".$rows3wr.")"; ?></option>
				 <?php } ?>
				 <?php } ?>
				 </select>
				</td>
			   </tr>
			   <?php } ?>
			   <?php if($value["cnote"]!="")
			   {
			   ?>
			<tr style="background:#ffcece;color:#000;font-size:14px;font-weight:bold;" id="tr-<?php echo $value["order_number"]; ?>"> 
			   <td colspan="8" style="text-align:center;">
			   Note for <?php $custName = $address->getName(); ?> <?php if(trim($custName)=="") { echo $customer->getName(); } else { echo $custName; } ?>'s order : <?php echo $value["cnote"]; ?> &nbsp; <a href="javascript:void(0);" onClick="showhir('<?php echo $value["order_number"]; ?>');">Minimize</a>
			   </td>
			   </tr>
			   <?php
			   }
			   
			       $torder_id = $value["order_number"];
				   $select_cnote="select cnote from mg_shipping_delivery_window where order_number='".$torder_id."' limit 0,1";
				   $conote=$connection->fetchOne($select_cnote);
				   
			   if($conote!="")
			   {
			   ?>
			<tr style="background:#ffcece;color:#000;font-size:14px;font-weight:bold;" id="tr-55<?php echo $value["order_number"]; ?>"> 
			   <td colspan="8" style="text-align:center;">
			   Customer Note : <?php echo $conote; ?> &nbsp; <a href="javascript:void(0);" onClick="showhir('55<?php echo $value["order_number"]; ?>');">Minimize</a>
			   </td>
			   </tr>
			   <?php
			   }
		   }
	    }
	  }
  ?>
<br/><br/>
</table>
</form>

<script>
function showhir(id)
{
   jQuery("#tr-"+id).hide();
}
</script>

<div id="a">

    <br/> 
	<div class="content-header">
      <table cellspacing="0">
        <tbody>
          <tr>
            <td style="width:50%;"><h3 class="icon-head head-report-sales-sales"><?php echo $this->__("Generate route plan");?></h3></td>
            <td class="form-buttons"><button style="" onClick="filterFormSubmit.submit()" class="scalable " type="button" id="id_<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"><span>Generate</span></button></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div>
	
      <div class="entry-edit">
        <form method="get" action="<?php echo Mage::helper('core/url')->getCurrentUrl();?>" id="filter_form">
          <?php /*?><input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /><?php */?>
          <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Filter</h4>
            <div class="form-buttons"></div>
          </div>
          <div id="sales_report_base_fieldset" class="fieldset">
            <div class="hor-scroll">
              <table cellspacing="0" class="form-list">
                <tbody>
                  <tr>
                    <td class="label"><label for="sales_report_from">Delivery Date<span class="required">*</span></label></td>
                    <td class="value"><input type="text" style="width:110px !important;" class=" required-entry input-text" title="From" value="<?php echo $_GET["from"]; ?>" id="sales_report_from" name="from" />
                      <img style="" title="Select Date" id="sales_report_from_trig" class="v-middle" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>skin/adminhtml/default/default/images/grid-cal.gif"> 
                      <script type="text/javascript">
            //<![CDATA[
                Calendar.setup({
                    inputField: "sales_report_from",
                    ifFormat: "%m/%e/%Y",
                    showsTime: false,
                    button: "sales_report_from_trig",
                    align: "Bl",
                    singleClick : true
                });
            //]]>
            </script></td>
                  </tr>
                  
                 
                </tbody>
              </table>
            </div>
          </div>
        </form>
      </div>
     
    </div>
	  
	  
	  <script type="text/javascript">
       	 //<![CDATA[
        	var filterFormSubmit  = new varienForm('filter_form');
         //]]>
        </script> 
      <script type="text/javascript"> new FormElementDependenceController({"sales_report_order_statuses":{"sales_report_show_order_statuses":"1"}}); </script> 
	  
	  
	  
	  <?php if(isset($_GET["from"])) {
	    $bfrom = explode("/",$_GET["from"]);
		$lfrom = $bfrom[1]."_".$bfrom[0]."_".$bfrom[2];
	   ?>
	  
       <table border=1 style="border-collapse:collapse">

<tr>
<th><b>Delivery Address</b></th>
<th><b>Time Window</b></th>
<th><b>Order Date</b></th>
<th><b>Order Number</b></th>
</tr>
<?php	  
	   $srb = '{"name":"'.$_GET["from"].'-auto","horizonDays":1,"driversSpeedPercent":100,"orders":[';	
	   $j=0;
	   for($i=0;$i<=0;$i++){
	   
	  
	   
     $kbt = $lfrom;
	
	 $kbt2 = (date("m-d-Y",strtotime("+$i days")));
	
	 
	 // $pDate = strtotime($kbt2.'- 1 week');
     // $pDate2 = date('Y-m-d',$pDate);

	 $sql        = "SELECT m.* FROM `mg_shipping_delivery_window` m  where m.`window` LIKE '%".$kbt."' order by m.`window`";
	 $rows = $connection->fetchAll($sql); 
	 $total_rows = count($rows);
	 
	 
	 if($total_rows>0)

	 {
	    $j=$j+1;
     }
	 
	 if($j%2==0)
	 {
	    $color='#fff';
	 }
	 else
	 {
	    $color='#cecece';
	 }
	  
	  $check=explode("-",$kbt2);
	  $check2[$i] =  $check[1];
	    
	  foreach ($rows as $value) {
	  
	  $sqlstatus     = "SELECT status FROM mg_sales_flat_order_grid  where increment_id='".$value["order_number"]."'";
		       $rowstatus = $connection->fetchOne($sqlstatus);
			   
	       if($value["order_number"]!="" && $value["order_number"]!='100006124' && $value["order_number"]!='100006123' && $value["order_number"]!='100006125' && $value["order_number"]!='100006126' && $value["order_number"]!='100006127' && $rowstatus!='canceled' )
		   {
		       $sql2        = "SELECT entity_id FROM mg_sales_flat_order_grid where increment_id='".$value["order_number"]."'";
		       $rows2 = $connection->fetchOne($sql2);
			  
			   $sql22       = "SELECT customer_id FROM mg_sales_flat_order_grid where increment_id='".$value["order_number"]."'";
		       $rows22 = $connection->fetchOne($sql22);
			   
			   
			   $sql222      = "SELECT entity_id FROM mg_sales_flat_order_grid where customer_id='".$rows22."' and increment_id!='".$value["order_number"]."'";
		       $rows222 = $connection->fetchOne($sql222);
			      
			   
			   $customer = Mage::getModel('customer/customer')->load($rows22); 
			   
			   $sql3  = "SELECT SUM(qty_ordered) FROM `mg_sales_flat_order_item` where `order_id`='".$rows2."'";
			   $rows3 = $connection->fetchOne($sql3); 
			   
			   
			   $order = Mage::getModel("sales/order")->load($rows2); //load order by order id 
			   $address = $order->getShippingAddress();
			   
			 
			   $temp = explode("|",$value['window']);
			   $temp3 = explode(".",$rows3);
			   $check22 = 0;
			   
			   if($temp[0]=="01_00pm_03_00pm")
			   {
			      $startm = 780;
				  $endm = 900; 
			   }
			   else if($temp[0]=="03_00pm_05_00pm")
			   {
			      $startm = 900;
				  $endm = 1020; 
			   }
			   
			   else if($temp[0]=="05_00pm_07_00pm")
			   {
			      $startm = 1020;
				  $endm = 1140; 
			   }
			   
			   else if($temp[0]=="07_00pm_09_00pm")
			   {
			      $startm = 1140;
				  $endm = 1260; 
			   }
			   
			   else
			   {
			       $startm = "780";
				   $endm = "1260";
			   }
			   
			   ?>
			   <tr style="background-color:<?php echo $color; ?>;">
			   <td <?php if($rows222 == "" ) {  echo 'style="color:#1c60ff;font-weight:bold;font-size:12px;"'; } ?> >
			    <?php
				echo $custAddr = $address->getStreetFull()."&nbsp;&nbsp;";
				echo $region2 = $address->getCity()."&nbsp;&nbsp;";
				echo $region = $address->getRegion()."&nbsp;&nbsp;";
				echo $country = $address["postcode"]; 
				 if($i==0) {
				
				  $ubr = $address->getStreetFull()." ".$address->getCity()." ".$address->getRegion()." ".$address["postcode"];
				 $srb.='{ "name":"'.$value["order_number"].'", "serviceTimeMin": 15, ';
				$srb.='"location":{"address":"'.$ubr.'"},"eligibleDays":[1],"timeWindows":[{"startMin":'.$startm.',"stopMin":'.$endm.'}]},';	
				 }
				 
				?>
				
				
				</td>
				<td><?php if($temp[1]!="") { echo $temp[0]; } else { echo "Flexible Time"; } ?></td>
				<td><?php if($temp[1]!="") { echo $temp[1]; } else { echo $temp[0]; } ?></td>
				<td><?php echo $value['order_number']; ?></td>
			   </tr>
			   <?php
			   
			    
		   }
	     }
	  }
	  
	 $srb = rtrim($srb, ",");
	 $srb.= ']}';
	 
	     $baseApiURL = "http://vrp.viamente.com/api/vrp/v2";
         $key = '3320e017-0d1b-4c67-a8e6-40d0767cc55e';

if ($key == 'YOUR_API_KEY_HERE') {
  die("Please edit example.php at line \"\$key = 'YOUR_API_KEY_HERE';\" and replace YOUR_API_KEY_HERE with your API key");
}


function assoc_array_from_json_file($fileName) {
  global $jsonPath;
  $str = '{
  "name": "Example deliveries",
  "label": "Your label text here",
  "workingDayStartMin": 0,
  "horizonDays": 2,
  "driversSpeedPercent": 100,
  "trafficProfile": {
    "name": "Lancaster",
    "description": "",
    "trafficRegions": [{
      "trafficLevelPercent": 50,
      "region": [{
        "lat": 34.707610,
        "lng": -118.175640
      }, {
        "lat": 34.708033,
        "lng": -118.231430
      }, {
        "lat": 34.661028,
        "lng": -118.243618
      }, {
        "lat": 34.626004,
        "lng": -118.216323
      }, {
        "lat": 34.631512,
        "lng": -118.157100
      }, {
        "lat": 34.693356,
        "lng": -118.151950
      }, {
        "lat": 34.700130,
        "lng": -118.161220
      }]
    }]
  },
  "loadUnitType": "Goods",
  "loadUnit2Type": "Pounds",
  "subfleetID": "flt-11111111-2222-3333-4444-555555555555",
  "orders": [{
    "name": "Nelson Torgersen",
    "loadUnits": 1,
    "loadUnits2": 10,
    "serviceTimeMin": 2,
    "location": {
      "address": "43534 Kirkland Ave, Lancaster, CA 93535, USA"
    },
    "eligibleDays": [1],
    "timeWindows": [{
      "startMin": 510,
      "stopMin": 540
    }],
    "importance": "higher",
    "skillsInclude": ["plumbing", "powertools"],
    "skillsExclude": ["landscaping"],
    "customFields": {
      "orderID": "XY-1234",
      "customerID": "AAA-9999",
      "phoneNumber": "(987) 654-3210"
    }
  }, {
    "name": "Jamie Rozman",
    "loadUnits": 2,
    "loadUnits2": 15,
    "serviceTimeMin": 2,
    "location": {
      "address": "1027 W Newgrove St, Lancaster, CA 93534, USA"
    },
    "eligibleDays": [2],
    "timeWindows": [{
      "startMin": 375,
      "stopMin": 450
    }]
  }, {
    "name": "Jessie Blewett",
    "loadUnits": 2,
    "loadUnits2": 18,
    "serviceTimeMin": 2,
    "location": {
      "address": "1235 W Kettering St, Lancaster, CA 93534, USA"
    },
    "eligibleDays": [1, 2],
    "timeWindows": [{
      "startMin": 510,
      "stopMin": 570
    }]
  }, {
    "name": "Marcie Ocon",
    "importance": "highest",
    "loadUnits": 1,
    "loadUnits2": 7,
    "serviceTimeMin": 2,
    "location": {
      "address": "45419 10th St W, Lancaster, CA 93534, USA"
    },
    "timeWindows": [{
      "startMin": 390,
      "stopMin": 390
    }]
  }, {
    "name": "Earlene Saur",
    "loadUnits": 2,
    "loadUnits2": 22,
    "serviceTimeMin": 0,
    "location": {
      "address": "44924 5th St E, Lancaster, CA 93535, USA"
    },
    "timeWindows": [{
      "startMin": 510,
      "stopMin": 600
    }]
  }, {
    "name": "Clayton Hervey",
    "loadUnits": 1,
    "loadUnits2": 4,
    "serviceTimeMin": 2,
    "location": {
      "address": "425 E Ave H 11, Lancaster, CA 93535, USA"
    },
    "timeWindows": [{
      "startMin": 540,
      "stopMin": 600
    }]
  }, {
    "name": "Earnestine Harnett",
    "loadUnits": 1,
    "loadUnits2": 7,
    "serviceTimeMin": 0,
    "location": {
      "address": "Earnestine Harnetts front door",
      "lat": 34.66239,
      "lng": -118.18351
    },
    "timeWindows": [{
      "startMin": 510,
      "stopMin": 660
    }]
  }, {
    "name": "Nelson Lufkin",
    "loadUnits": 3,
    "loadUnits2": 38,
    "serviceTimeMin": 0,
    "location": {
      "address": "43420 22nd St W, Lancaster, CA 93536, USA"
    },
    "timeWindows": [{
      "startMin": 480,
      "stopMin": 540
    }]
  }, {
    "name": "Jerri Ertl",
    "loadUnits": 3,
    "loadUnits2": 32,
    "serviceTimeMin": 2,
    "location": {
      "address": "44044 36th St W, Lancaster, CA 93536, USA"
    },
    "timeWindows": [{
      "startMin": 450,
      "stopMin": 510
    }]
  }]
}';
  return json_decode($str, true); // true = decode as associative array
}

function json_encode_ex($data) {
  return json_encode($data, JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP);
}

function json_indent($json) {
  $result      = '';
  $pos         = 0;
  $strLen      = strlen($json);
  $indentStr   = '  ';
  $newLine     = "\n";
  $prevChar    = '';
  $outOfQuotes = true;

  for ($i=0; $i<=$strLen; $i++) {
    // Grab the next character in the string.
    $char = substr($json, $i, 1);

    // Are we inside a quoted string?
    if ($char == '"' && $prevChar != '\\') {
      $outOfQuotes = !$outOfQuotes;

    // If this character is the end of an element,
    // output a new line and indent the next line.
    } else if(($char == '}' || $char == ']') && $outOfQuotes) {
      $result .= $newLine;
      $pos --;
      for ($j=0; $j<$pos; $j++) {
        $result .= $indentStr;
      }
    }

    // Add the character to the result string.
    $result .= $char;

    // If the last character was the beginning of an element,
    // output a new line and indent the next line.
    if (($char == ',' || $char == '{' || $char == '[') && $outOfQuotes) {
      $result .= $newLine;
      if ($char == '{' || $char == '[') {
        $pos ++;
      }

      for ($j = 0; $j < $pos; $j++) {
        $result .= $indentStr;
      }
    }

    $prevChar = $char;
  }
  return $result;
}


function executeRest($url, $method, $key, $data = "") {
  $headers = array(
    'Accept: application/json',
    'Content-Type: application/json'
  );

  $url .= '?key='.$key;

  $handle = curl_init();
  curl_setopt($handle, CURLOPT_URL, $url);
  curl_setopt($handle, CURLOPT_HTTPHEADER, $headers);
  curl_setopt($handle, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($handle, CURLOPT_SSL_VERIFYHOST, false);
  curl_setopt($handle, CURLOPT_SSL_VERIFYPEER, false);
  curl_setopt($handle, CURLOPT_CONNECTTIMEOUT, 10);
  curl_setopt($handle, CURLOPT_TIMEOUT, 360);

  switch($method)
  {
    case 'GET':
    break;

    case 'POST':
    curl_setopt($handle, CURLOPT_POST, true);
    curl_setopt($handle, CURLOPT_POSTFIELDS, $data);
    break;

    case 'PUT':
    curl_setopt($handle, CURLOPT_CUSTOMREQUEST, 'PUT');
    curl_setopt($handle, CURLOPT_POSTFIELDS, $data);
    break;

    case 'DELETE':
    curl_setopt($handle, CURLOPT_CUSTOMREQUEST, 'DELETE');
    break;
  }

  $response = curl_exec($handle);
  $status = curl_getinfo($handle, CURLINFO_HTTP_CODE);
 
  if(php_sapi_name() != "cli") {
    flush();
    ob_flush();
  }

  return json_indent($response);
}
         $routeplanRes = executeRest($baseApiURL."/routeplans", 'POST', $key, $srb);
?>
<br/><br/>
</table>
     <?php } ?>
</div>
<?php } } ?>
<script type="text/javascript">
    function pickfun(oid)
	{
	   jQuery('#trid').val(oid);
	   jQuery('#frmpick').submit();
	}
</script>
