<?php
/************************************************************************
 * 
 * jtechextensions @ J-Tech LLC.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.jtechextensions.com/LICENSE-M1.txt
 *
 * @package    Inventory Report
 * @copyright  Copyright (c) 2012-2013 jtechextensions @ J-Tech LLC. (http://www.jtechextensions.com)
 * @license    http://www.jtechextensions.com/LICENSE-M1.txt
************************************************************************/
?>

<div class="entry-edit">
	<div class="content-header">
	    <table cellspacing="0">
	        <tbody>
		        <tr>
		            <td style="width: 50%;">
		            	<h3 class="icon-head head-manager-view">Jtech Advanced Reporting</h3>
		            </td>
		            <td class="form-buttons">
		            	<button style="" onclick="editForm.submit();" class="scalable save" type="button" >
		            		<span>Update Settings</span>
		            	</button>
		            </td>
		        </tr>
	    	</tbody>
	    </table>
	</div>
	
	<form method="post" action="<?php echo $this->getUrl('*/*/save'); ?>" id="edit_form">
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<div class="entry-edit-head">
	   		<h4 class="icon-head head-edit-form fieldset-legend">Settings</h4>
	    	<div class="form-buttons"></div>
		</div>
    	<div id="attributes_form_" class="fieldset ">
	    	<div class="hor-scroll">
	        	<table cellspacing="0" class="form-list">
    	        	<tbody>
        	        	<tr>
        					<td class="label" colspan="2">
        						The cost attribute code <?php echo $this->getCostStatement() ?>
        					</td>
    					</tr>
						<tr>
        					<td class="label">
        						<label for="cost_att_code">Product Cost Attribute Code</label>
        					</td>
    						<td class="value">
	        					<input type="text" class=" input-text required-entry" value="<?php echo $this->getCostAttCode() ?>" name="cost_att_code" id="cost_att_code">
	        					<p id="note_cost_att_code" class="note"><span>The Magento default code is "cost". Change only if the cost attribute code has been modified.</span></p>
	        				</td>
    					</tr>
    					<tr><td colspan = "2">&nbsp;</td></tr>
    					<tr>
        					<td class="label" colspan="2">
        						The name attribute code <?php echo $this->getNameStatement() ?>
        					</td>
    					</tr>
						<tr>
        					<td class="label">
        						<label for="name_att_code">Product Name Attribute Code</label>
        					</td>
    						<td class="value">
	        					<input type="text" class=" input-text required-entry" value="<?php echo $this->getNameAttCode() ?>" name="name_att_code" id="name_att_code">
	        					<p id="note_name_att_code" class="note"><span>The Magento default code is "name". Change only if the product name attribute code has been modified.</span></p>
	        				</td>
    					</tr>
	            	</tbody>
	        	</table>
    	    </div>
    	</div>
	</form>
	
	<script type="text/javascript">
    	editForm = new varienForm('edit_form', '');
	</script>
</div>
<?php echo $this->getChildHtml('form_after');?>
