<?php
/**
 * customize by: http://istockphp.com
 * like us on facebook: http://www.facebook.com/pages/Istockphp/235451993242578
 * follow us on twitter: http://twitter.com/istockphp
 */
?>
<style type="text/css">
.customer-accountpage-index .PrestoPremier label{  color: #000; font-size: 13px; font-weight: bold;}
.div1 , .customer_prod{ border: 1px solid #bbb;  }
.PrestoPremier {background: none repeat scroll 0 0 #fff;border: 1px solid #bbb;clear: both;min-height: 123px;padding: 10px;width: 37%;}
.div1{float: left; padding:10px;}
.customer_prod{ float:right;padding:10px;}
.note { color: #df280a; border: 1px solid #f16048; font-size: 14px; padding: 10px 0; background:url(http://localhost/Demo/magento-1.8.1.0/magento/skin/frontend/default/default/images/i_msg-error.gif)scroll 6px center #faebe7 no-repeat;   padding: 10px 0 10px 30px; margin:10px 0;} 
</style>
<div class="page-title">
    <h1><?php echo $this->__('PrestoPremier Membership (Free Delivery)') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $a = Mage::getSingleton('customer/session')->isLoggedIn();
 	  $connection = Mage::getSingleton('core/resource')->getConnection('core_read');
	  $customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
	  $productTable = 'mg_customer_subsciption';
	  $query = "SELECT * FROM " . $productTable . " WHERE customer_id = '".$customer_id."'";
	  $result = $connection->query($query);
	  $row = $result->fetch();
//echo '<pre>';print_r($row);
 ?>	<?php if($row['active'] == 'Yes'){?>
    <div class="PrestoPremier" style=" border: 1px solid #bbb;    padding: 10px; ">
        <div class="div1">
 	        <label style="color:#1e7ec8"><u>Schedule </u></label>
            <table cellpadding="3" cellspacing="3" width="300" style="padding:10px 0;">
            <tr>
                <td colspan="2"><label>Start date:</label>  </td><td><?php echo date('M , d , Y',strtotime($row['start_date']));?></td>
            </tr>
            <tr>
                <td colspan="2"><label>Expire date:</label>  </td><td><?php echo date('M , d , Y',strtotime($row['expiry_date']));?></td>
            </tr>
            <tr>
                <td colspan="2"><label>Duration: </label> </td><td><?php echo $row['duration'];?></td>
            </tr>
            <tr>
                <td colspan="2"><label>Active:</label>	  </td><td><?php echo $row['active'];?></td>
            </tr>
            </table>
        </div>
        <div class="customer_prod" style="display:none">
	        <label style="color:#1e7ec8"><u>Purchased Item</u></label>
            <table cellpadding="3" cellspacing="3" width="300" style="padding:10px 0;">
            <tr><td><label>Product Name:</label></td><td></td></tr>
            <tr><td><label>Sku:</label></td><td></td></tr>
            <tr><td><label>Qty:</label></td><td></td></tr>
            
            </table>
        </div>
    </div>
    <?php } else{ echo 'You have not subscribed PrestoPremier Membership (Free Delivery). if you want to be a member click here and Purchase this subscription';?>
	<a href="<?php echo 'https://www.prestofreshgrocery.com/newstaging/free-shipping-subscription.html';?>">Click Here</a>
	<?php 	}?>
    <?php if($row['active'] == 'No' && $row['active'] != ''){?>
    <p class="note"><span>Your subscription will expire.</span> </p><?php } ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account/') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>

<script type="text/javascript">
</script>
