<?php
		 error_reporting(E_ALL);
		 ini_set('display_errors', 1);
		 require 'vendor/autoload.php';

	    $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
	    define("AUTHORIZENET_API_LOGIN_ID", "85z7aV7XB");
		define("AUTHORIZENET_TRANSACTION_KEY", "3bWR6zZ8hx9h34zs");
		define("AUTHORIZENET_SANDBOX", false);

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body>
<?php
	$to="";
	$from="";
	$show_order_statuses = 0;
	$orserstatus = "";
	$result_order = 0;

	if(!empty($_REQUEST['from']) ){
		/*====================== Start Code for Magento Orders Product =====================*/
		//echo "<pre>";
		$orders_row = array();

		$to=$_REQUEST['to'];
		$from=$_REQUEST['from'];

		$rr=explode("/",$from);
		$adate=$rr[2]."-".$rr[0]."-".$rr[1];

		$to_date = date('Y-m-d' . ' 00:00:00', strtotime($to));
		$from_date = date('Y-m-d' . ' 00:00:00', strtotime($from));

		$custname=$_GET["custname"];
	}

	if(!isset($_GET["custname"]))
	{
		if($from=="" && $to=="") {
		      $to=date('m/d/Y');
			  $from=date('m/d/Y',strtotime($to . " -1 day"));
			  $_GET["from"] = $from;
			  $from_date = date('Y-m-d' . ' 00:00:00', strtotime($from));
		    }
	}
	?>
<div id="anchor-content" class="middle">
  <div id="page:main-container">
    <div class="content-header">
      <table cellspacing="0">
        <tbody>
          <tr>
            <td style="width:50%;"><h3 class="icon-head head-report-sales-sales"><?php echo $this->__("Daily Sales Report");?></h3></td>
            <td class="form-buttons"><button style="" onclick="filterFormSubmit.submit()" class="scalable " type="button" id="id_<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"><span>Show Report</span></button></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div>
      <div class="entry-edit">
        <form method="get" action="<?php echo Mage::helper('core/url')->getCurrentUrl();?>" id="filter_form">
          <?php /*?><input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /><?php */?>
          <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Filter</h4>
            <div class="form-buttons"></div>
          </div>
          <div id="sales_report_base_fieldset" class="fieldset">
            <div class="hor-scroll">
              <table cellspacing="0" class="form-list">
                <tbody>
                  <tr>
                    <td class="label"><label for="sales_report_from">Delivery Date<span class="required">*</span></label></td>
                    <td class="value"><input type="text" style="width:110px !important;" class=" input-text" title="From" value="<?php echo $from; ?>" id="sales_report_from" name="from" />
                      <img style="" title="Select Date" id="sales_report_from_trig" class="v-middle" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>skin/adminhtml/default/default/images/grid-cal.gif">
                      <script type="text/javascript">
            //<![CDATA[
                Calendar.setup({
                    inputField: "sales_report_from",
                    ifFormat: "%m/%e/%Y",
                    showsTime: false,
                    button: "sales_report_from_trig",
                    align: "Bl",
                    singleClick : true
                });
            //]]>
            </script></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </form>
      </div>
    </div>


	<?php if(isset($_GET["oid"]) && $_GET["oid"]!="" ) {

     $order = Mage::getModel('sales/order')->load($_GET["oid"], 'increment_id');
	 $order->getAllVisibleItems();
	 $address = $order->getShippingAddress();
	 $address2 = $order->getBillingAddress();
	 $orderValue = $order->getSubtotal();
	 $orderValue2 = $order->getBaseGrandTotal();
?>

<style>
.page
{
   width:90%;
}
td, th
{
   padding:5px !important;
   font-size:12px;
   color:#000;
}
table
{
   border-color:#000;
}
th
{
   color:#000;
}
</style>
<div style="border-bottom:3px solid #dfdfdf;margin-bottom:5px;" >
<h3 class="icon-head head-manage-blog" style="padding-left:0px;color:#eb5e00;">Order Details ( <?php echo $_GET["oid"]; ?> )</h3>
<?php
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url77 = explode("?oid=",$currentUrl);

?>

<a href="<?php echo $url77[0]; ?>" > Back to Order Support Report </a>

</div>
	 <b> Delivery Address :- </b>
	             <?php echo $custName = $address->getName()."&nbsp;&nbsp;";
				echo $custAddr = $address->getStreetFull()."&nbsp;&nbsp;";
				echo $region2 = $address->getCity()."&nbsp;&nbsp;";
				echo $region = $address->getRegion()."&nbsp;&nbsp;";
				echo $country = $address["postcode"]; ?>

	 <br/><br/><b> Billing Address :- </b>
	  <?php echo $custName = $address2->getName()."&nbsp;&nbsp;";
				echo $custAddr = $address2->getStreetFull()."&nbsp;&nbsp;";
				echo $region2 = $address2->getCity()."&nbsp;&nbsp;";
				echo $region = $address2->getRegion()."&nbsp;&nbsp;";
				echo $country = $address2["postcode"]; ?>
		<br/><br/>
		<b> Customer :- </b>
		<?php echo $custName; ?>
		&nbsp; &nbsp;


		<b> Customer Telephone :- </b>
		<?php echo $address->getTelephone(); ?>
		&nbsp; &nbsp;
		<br/><br/>

		<script>
function dorefund2(itemid)
		{
		   bcd=(jQuery('#chkref-').is(':checked'));

		   if(bcd==true)
		   {
			  bcd=1;
		   }
		   else
		   {
			 bcd=0;
		   }
			       jQuery.ajax({
				   url: "<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>ajaxel.php?rand="+Math.random()+"&itemid="+itemid+"&refund="+bcd,
				   context: document.body
					}).done(function(data) {
					 if(data==1)
					 {
						alert("Order Has Been Removed From Specialty Dept. Report ");
					 }
					 else if(data==0)
					 {
					   alert("Order Has Been Added to Specialty Dept. Report ");
					 }
				 });
		  		}
</script>


	  <?php
	  		$sql55555 = "SELECT `window` FROM `mg_shipping_delivery_window` where `order_number`='".$_GET["oid"]."'";
			$rows55555 = $connection->fetchOne($sql55555);
			 $temp = explode("|",$rows55555);

			  $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
			  $sel_el="select exclude_lables from mg_shipping_delivery_window where order_number='".$_GET["oid"]."'";
			  $el=$connection->fetchOne($sel_el);

		 ?>

		 <b> Delivery Date :- </b>

		&nbsp; &nbsp;<b> Delivery Time :- </b>
			 <?php if($temp[1]=="") { echo 'Flexible Time'; } else { echo $temp[0]; } ?>

			   <div style="padding:5px;background:red;color:#fff;font-weight:bold;margin-bottom:10px;"> <input type="checkbox" name="chkref-" value="1" id="chkref-" OnChange="dorefund2(<?php echo $_GET["oid"]; ?>);" <?php if($el==1) { ?> checked="checked" <?php } ?>  > Remove From Specialty Dept. Report </div>

			 <form method="get" action="" id="frmdates" name="frmdates" >
			 <div style="margin-top:10px;">
			 Change Date :- <input type="text" name="changedate" value="<?php if($temp[1]=="") { echo $temp[0]; } else { echo $temp[1]; } ?>" > (dd_mm_yyyy)
			 </div>
			  <div style="margin-top:10px;" >
			 Change Time :- <input type="text" name="changetime" value="<?php if($temp[1]=="") { echo 'Flexible Time'; } else { echo $temp[0]; } ?>" >  ( Note :- For Flexible Time Keep It Blank )
			  </div>
			  <div style="margin-top:10px;">
			  <button style="margin-top:15px;" onclick="dofrmsubmit();" class="scalable " type="button" id=""><span>Change Date</span></button>
			  </div>
			  <input type="hidden" name="oid" id="oid" value="<?php echo $_GET["oid"]; ?>" />
			   <input type="hidden" name="from" id="from" value="<?php echo $_GET["from"]; ?>" />
			 </form>

			 <script>
			 function dofrmsubmit()
			 {
			     document.getElementById("frmdates").submit();
			 }
			 </script>

<?php
   $value["order_number"] = $_GET["oid"];
   if($value["order_number"]!="")
		   {
		       $sql2        = "SELECT entity_id FROM mg_sales_flat_order_grid where increment_id='".$value["order_number"]."'";
		       $rows2 = $connection->fetchOne($sql2);
			   echo "<br/>";

				$sql3 = "SELECT mei.value,msi.item_id,msi.selref,msi.txtref,msi.refund,msi.product_id,msi.price,msi.row_total,msi.qty_ordered,msi.name,msi.sku FROM `mg_sales_flat_order_item` msi
			    left join mg_catalog_product_entity_int mei on msi.product_id = mei.entity_id and mei.attribute_id =  251
			    where msi.`order_id`='".$rows2."'";

			   $rows3 = $connection->fetchAll($sql3);

			   $sel_check_operation="select * from orderoperation where oid='".$_GET["oid"]."'";
			   $rows3heck_operation = $connection->fetchAll($sel_check_operation);

			   if(count($rows3heck_operation>=1))
			   {
			   ?>
			   <table border=1 cellpadding="5" cellspacing="5" border="1" style="border-collapse:collapse;margin-bottom:20px;margin-top:15px;" >

			   <tr style="background:red;color:#fff;">
			   <th> Order Edits </th>
			   </tr>
			   <?php
			   foreach ($rows3heck_operation as $value3) {
			   ?>
			   <tr>
			   <td> <?php echo $value3["operation"]; ?></td>
			   </tr>
			   <?php } ?>
			   </table>
			   <?php
			   }
			   ?>
			   <br/><br/><b> Order Items </b>
			   <table border=1 cellpadding="5" cellspacing="5" border="1" style="border-collapse:collapse" >
			   <tr>
			   <th >Product Name</th>
			   <th>Sku</th>
			   <th>Price</th>
			   <th>Qty</th>
			   <th>Subtotal</th>
			   <th>Product Type</th>
			   <th>Found / Not Found</th>
				<th>Packed / Not Packed</th>
				<th>Substitute</th>
				<th>Refund</th>
				<th>Picker Mistake</th>
			   <th>Change Qty</th>
			   <th>Remove Item</th>
			   </tr>

			   <?php
			   $rr=0;
			   foreach ($rows3 as $value3) {

			    $sel_status="select status from supervision where item_id='".$value3["item_id"]."'";
				$nstatus=$connection->fetchOne($sel_status);

				$sel_log="select log2 from supervision where item_id='".$value3["item_id"]."'";
				$nlog=$connection->fetchOne($sel_log);

				$sel_subs="select substitute from supervision where item_id='".$value3["item_id"]."'";
				$nsubs=$connection->fetchOne($sel_subs);


				  if($nlog==1)
				  {
				     $nlog = 'Packed';
				  }
				  else
				  {
				     $nlog = 'Not Packed';
				  }

				$_resource = Mage::getSingleton('catalog/product')->getResource();
				$optionValue1 = $_resource->getAttributeRawValue($value3["product_id"],'protype', Mage::app()->getStore());

				$product = Mage::getModel('catalog/product')->setStoreId($store_id)->setProtype($optionValue1);
                $optionLabel1 = $product->getAttributeText('protype');

				$optionValue4 = $_resource->getAttributeRawValue($value3["product_id"],'vendor_product_id', Mage::app()->getStore());

				$rr = $rr + $value3["row_total"];
			   ?>

			    <tr>
				<td><?php echo $value3["name"]; ?></td>
				<td><?php echo $value3["sku"]; ?></td>
				<td>$<?php echo number_format($value3["price"], 2, '.', ''); ?></td>
				<td><?php echo round($value3['qty_ordered'],0); ?></td>
				<td>$<?php echo number_format($value3["row_total"], 2, '.', ''); ?></td>
				<td><?php echo $optionLabel1; ?></td>
				<td><?php echo $nstatus; ?></td>
				<td><?php echo $nlog; ?></td>
				<td><?php echo $nsubs; ?></td>
				<td style="font-weight:bold;font-size:12px;"><div style="color:#000;margin-top:15px;"> <input type="checkbox" name="chkref-<?php echo $value3['item_id']; ?>" id="chkref-<?php echo $value3['item_id']; ?>" <?php if($value3['refund']==1) { echo "checked"; } ?> value="<?php echo $value3['item_id']; ?>" onClick="dorefund(<?php echo $value3['item_id']; ?> )" /> Refund Item </div></td>

				<td style="font-weight:bold;font-size:12px;">
				Picker Mistake

				<select name="selectref-<?php echo $value3['item_id']; ?>" id="selectref-<?php echo $value3['item_id']; ?>">
				<option value=""> Select </option>
				<option value="Expired Product" <?php if($value3['selref']=="Expired Product") { echo "selected"; } ?> > Expired Product </option>
				<option value="Incorrect Item" <?php if($value3['selref']=="Incorrect Item") { echo "selected"; } ?> > Incorrect Item </option>
				<option value="Missing Item" <?php if($value3['selref']=="Missing Item") { echo "selected"; } ?> > Missing Item </option>
				<option value="Packing Issue" <?php if($value3['selref']=="Packing Issue") { echo "selected"; } ?> > Packing Issue </option>
				<option value="Other" <?php if($value3['selref']=="Other") { echo "selected"; } ?> > Other </option>
				</select>

				<textarea name="txtref-<?php echo $value3['item_id']; ?>" id="txtref-<?php echo $value3['item_id']; ?>" onBlur="dorefundp(<?php echo $value3['item_id']; ?> )" style="margin-top:10px;"><?php echo $value3['txtref']; ?></textarea>
				<br/>
				</td>


				<td>  <form method="get" action="" name="editform<?php echo $value3["item_id"]; ?>" id="editform<?php echo $value3["item_id"]; ?>"><input type="text" style="width:20px;" name="qty_set" value="<?php echo round($value3['qty_ordered'],0); ?>" /><br/><button style="margin-top:15px;" onclick="gosubmit(<?php echo $value3["item_id"]; ?>)" class="scalable " type="button" id="id_sxIHHR43YtHVy4TP"><span>Change Qty</span></button><input type="hidden" name="item_id" id="item_id" value="<?php echo $value3["item_id"]; ?>" />
				<input type="hidden" name="qty_orderd" id="qty_orderd" value="<?php echo round($value3["qty_ordered"],0) ?>" />
				<input type="hidden" name="pro_id" id="pro_id" value="<?php echo round($value3["product_id"],0) ?>" />
				<input type="hidden" name="rowtotal" id="rowtotal" value="<?php echo round($value3["row_total"],2) ?>" />
				<input type="hidden" name="proprice" id="proprice" value="<?php echo round($value3["price"],2) ?>" />
				<input type="hidden" name="oid" id="oid" value="<?php echo $_GET["oid"]; ?>" />
			  </form>

			 <?php

			  $currentUrl = Mage::helper('core/url')->getCurrentUrl();
			  ?>
       			  <td><a href="<?php echo $currentUrl; ?>&detl=<?php echo $value3["item_id"]; ?> " onClick="return confirm('Are you sure you want to remove this item ?');"> Remove Item</a></td>

			   <script type="text/javascript">
       	       function gosubmit(id)
			   {
			      jQuery('#editform'+id).submit();
			   }
</script> </td>
				</tr>
			   <?php
			   }
			   ?>
			   <tr>
			     <td></td>
			   <td style="text-align:right;" colspan="4">
			   <b>
			   <br/>
			    Total : $<?php echo number_format($rr, 2, '.', ''); ?><br/> <br/>
			   Original Subtoal : $<?php echo number_format($orderValue, 2, '.', ''); ?>  <br/>  <br/>
			   Grandtotal :  $<?php echo number_format($orderValue2, 2, '.', ''); ?>  <br/>
			   </b>
			  <br/>
			   </td>
			   <td colspan="3" style="background:red;color:#fff;font-size:15px;font-weight:bold;"> Difference Amount : $<?php if($rr!=$orderValue) { echo round($orderValue-$rr,2); } ?></td>
			   </tr>
			    </table>
			   <?php
		   }

	  exit(0);
	  }
	?>
	<?php
	  if(!empty($_REQUEST['from']) || !empty($_REQUEST['custname']) ){ ?>
	  <style>
	.page
	{
	   width:90%;
	}
	td, th
	{
	   padding-top:5px !important;
	   padding-left:5px !important;
	   padding-right:5px !important;
	   padding-bottom:5px !important;
	   font-size:11px;
	   font-weight:bold;
	}
	th
	{
	   background:#999;
	}
	table
	{
	   border-collapse:collapse;
	}
	</style>


	  <table border=1 style="border-collapse:collapse;font-size:11px;">
		<tr>
		<th><b>Order Number</b></th>
		<th><b>Order Date</b><br/>(Y-m-d h:m:s)</th>
		<th><b>Delivery Date</b></th>
		<th><b>Ship To</b></th>
		<th><b>Status</b></th>
		<th><b>Invoice</b></th>
		<th><b>Product Sales</b></th>
		<th><b>Total Paid</b></th>
		<th><b>Discount</b></th>
		<th><b>Delivery Fee</b></th>
		<th><b>Tax</b></th>
		<th><b>Tip</b></th>
		<th><b>Refund Amount</b></th>
		<th><b>Total</b></th>
		</tr>
<?php

	   $j=0;
	                $ps=0;
					$tpr=0;
					$ds=0;
			        $df=0;
					$tax=0;
					$atip=0;
					$totalls=0;
					$mt=0;
					$raf=0;

	   for($i=1;$i<=1;$i++){
	   $kb=0;
	   $Date1 = $adate;
							$date = new DateTime($Date1);
							$date->add(new DateInterval('P'.$kb.'D')); // P1D means a period of 1 day
							$kbt = $date->format('Y-m-d');
	$sql = "SELECT m.increment_id,m.created_at,mw.window ,m.entity_id,m.base_subtotal,m.base_total_invoiced,m.discount_amount,m.shipping_amount,m.base_tax_amount,m.ramount FROM `mg_sales_flat_order` m
	left join mg_shipping_delivery_window mw on m.increment_id = mw.order_number
	where m.`created_at` LIKE '%".$kbt."%' ";
	 $rows = $connection->fetchAll($sql);
	  $check=explode("-",$kbt2);
	  $check2[$i] =  $check[1];

	  foreach ($rows as $value) {

	  $temp = explode("|",$value['window']);
			   $temp3 = explode(".",$rows3);
			   $check22 = 0;

			 //  print_r($temp);

			   if($temp[1]=="")
			   {
			     $ddates = $temp[0];
			   }
			   else
			   {
			    $ddates = $temp[1];
			   }

			   if($value["discount_amount"]>0)
			   {
			      $value["discount_amount"] = $value["discount_amount"] - ($value["discount_amount"]*2);
			   }

	           $order = Mage::getModel("sales/order")->load($value["entity_id"]); //load order by order id
			   $address = $order->getShippingAddress();
			   $invoiceIds = $order->getInvoiceCollection()->getAllIds();

			   $sqlstatus  = "SELECT tip FROM drivlist  where ordernumber='".$value["increment_id"]."'";
					$number["tip"] = $connection->fetchOne($sqlstatus);
					$ps=$ps+$value["base_subtotal"];
					$tpr=$tpr+$value["base_total_invoiced"];
					$ds=$ds+$value["discount_amount"];
			        $df=$df+$value["shipping_amount"];
					$tax=$tax+$value["base_tax_amount"];
					$atip=$atip+$number["tip"];
					$raf=$raf+$value["ramount"];
					$totalls = round(($number["tip"]+$value["base_tax_amount"]+$value["shipping_amount"]+$value["base_subtotal"])+$value["discount_amount"],2);
					$mt = $mt+$totalls;
	  ?>
	  <tr>
	  <td><?php echo $value["increment_id"]; ?></td>
	   <td><?php echo $value["created_at"]; ?></td>
	   <td><?php echo $_REQUEST['from']; ?> | <?php if($temp[1]=="") { echo 'Flexible Time'; } else { echo $temp[0]; } ?></td>
	   <td><?php echo $custName = $address->getName(); ?></td>
	   <td><?php echo $order->getStatus(); ?></td>
	   <td><?php echo $invoiceIds["0"]; ?></td>
	   <td>$<?php echo round($value["base_subtotal"],2); ?></td>
	    <td>$<?php echo round($value["base_total_invoiced"],2); ?></td>
		<td style="color:red;">$<?php echo round($value["discount_amount"],2); ?></td>
		<td>$<?php echo round($value["shipping_amount"],2); ?></td>
		<td>$<?php echo round($value["base_tax_amount"],2); ?></td>
		<td>$<?php echo round($number["tip"],2); ?></td>
		<td>$<?php echo round($value["ramount"],2); ?></td>
		<td>$<?php echo round(($number["tip"]+$value["base_tax_amount"]+$value["shipping_amount"]+$value["base_subtotal"])+$value["discount_amount"],2); ?></td>

	  </tr>
	  <?php
	  }
	}
  ?>
   <tr>
	  <td></td>
	   <td></td>
	   <td></td>
	   <td></td>
	   <td></td>
	   <td></td>
	   <td>$<?php echo round($ps,2); ?></td>
	    <td>$<?php echo round($tpr,2); ?></td>
		<td style="color:red;">$<?php echo round($ds,2); ?></td>
		<td>$<?php echo round($df,2); ?></td>
		<td>$<?php echo round($tax,2); ?></td>
		<td>$<?php echo round($atip,2); ?></td>
		<td>$<?php echo round($raf,2); ?></td>
		<td>$<?php echo round($mt,2); ?></td>
	  </tr>

<br/><br/>
</table>
	  <?php } ?>
	<script type="text/javascript">
       	 //<![CDATA[
        	var filterFormSubmit  = new varienForm('filter_form');
         //]]>
        </script>
      <script type="text/javascript"> new FormElementDependenceController({"sales_report_order_statuses":{"sales_report_show_order_statuses":"1"}}); </script>
</body>
</html>