<style>
.block-title2 {
   /* background: #fce704 none repeat scroll 0 0 !important;
    border: 1px solid #fce704;*/
	background: grey none repeat scroll 0 0 ;
    border: 1px solid grey;
    border-radius: 8px;
    color: #000;
    padding: 10px;
    position: relative;
}
.block-title2 strong {
    color: #000;
    font-size: 14px;
    font-weight: bold;
    line-height: 26px;
}
.block-content{
	   border-bottom: 1px solid #ccc;
    border-left: 1px solid #ccc;
    border-radius: 4px;
    border-right: 1px solid #ccc;
    margin-top: -3px;
    padding: 14px;
	
}
#survey > form {
    line-height: 35px;
}
#survey input {
    height: 43px;
}
.qn_desc{
	font-size:12px;
	display:none;
}
.radioBtn{margin-right:15px;}
.block.block-related {
    margin-top: 20px;
}

@media only screen and (max-width : 480px)   {
	.block.block-related{width:84%;}
	textarea{width:100%;}
	
	
}

</style>
<?php $surveyDetails = $this->getSurveyDetails(); ?>
<?php if( $surveyDetails!=null): ?>
<div class="block block-related">
	
    <div class="block-title2">
		<?php
			if($surveyDetails->getData('survey_id') == 1){
		?>
        <strong><span style="color:#fff;">Order Survey for Order #<?php echo $_GET['order']; ?></span></strong>
		<?php
			}else{
			?>	
		<strong><span ><?php echo $surveyDetails->getData('survey_name'); ?></span></strong>
			<?php
			}
		?>
    </div>
    
    <div class="block-content">
        <div id="survey" class="empty">
		
		<?php 
			$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
			$sel_ref="select survey_result_id from mg_survey_result where order_id='".$_GET['order']."'";
			$ref=$connection->fetchOne($sel_ref);
			if($ref=="")
			{
		?>
            <form action="<?php echo $this->getSurveySubmitUrl(); ?>" name="survey_result" method="post">
            <?php $cnt=1; ?>
            <?php foreach( $this->helper('surveymanager')->getSurveyRelations(
                            $surveyDetails->getData('survey_id')) as $key=> $surveyRelation): ?>
                      <?php $question = $this->helper('surveymanager')
                              ->getSurveyQnById( $surveyRelation->getData('survey_qn_id')) ?> 
                      <div style="color:red;font-weight:bold;color:#619313"><?php echo $cnt.':'?> <?php echo $question->survey_qn_title; ?></div>
					  <span class="qn_desc">( <?php echo $question->survey_qn_desc; ?> )</span>
                      <?php $answers = $this->helper('surveymanager')->getSurveyAnswersByQid($question->survey_qn_id) ?>
                      <?php $ansType = $question->survey_ans_type; ?>
					  
                       <input type="hidden" id="survey_ans_type" name="survey_ans_type[<?php echo $question->survey_qn_id; ?>]" value="<?php echo $ansType; ?>" />   
                       
                       <div style="padding-bottom:10px;color:#000;">     
                          <?php if($ansType=="9" ||  $ansType=="6"): ?>  
                             <select id="survey_value" name="survey_values[<?php echo $question->survey_qn_id; ?>]">
                          <?php endif; ?>                          
                              <?php if( $ansType=="6"): ?>    
                                  <option value="yes">Yes</option>
                                  <option value="no">No</option>
                              <?php endif; ?>
                              
                              <?php 
								$count = 1;
								foreach($answers as $answer): ?>
                                  <?php if( $ansType=="9"): ?>  
                                      <option value="<?php echo $answer->survey_ans_id; ?>">
                                        <?php echo $answer->survey_ans_title; ?>
                                      </option>
                                  <?php endif; ?>
                                  <?php if( $ansType=="7"): ?> 
									<?php
									if( ($surveyDetails->getData('survey_id') == 1) && ($count == 1) && ($question->survey_qn_id ==1) )
									{
										//echo "Question id is ".$question->survey_qn_id;
										echo "<span style=margin-right:10px;>Not Satisfied</span>";	
									}
									if( ($surveyDetails->getData('survey_id') == 1) && ($count == 1) && ($question->survey_qn_id ==2) )
									{
										//echo "Question id is ".$question->survey_qn_id;
										echo "<span style=margin-right:25px;>Not Likely</span>";	
									}
									if( ($surveyDetails->getData('survey_id') == 1) && ($count == 1) && ($question->survey_qn_id ==5) )
									{
										//echo "Question id is ".$question->survey_qn_id;
										echo "<span style=margin-right:10px;>Not Satisfied</span>";	
									}
									?>
										<span class="radioBtn">
                                      <input type="radio" name="survey_values[<?php echo $question->survey_qn_id; ?>]" value="<?php echo $answer->survey_ans_id; ?>"/>
                                      <?php echo $answer->survey_ans_title; ?>
									  </span>
									 <?php
										//echo "Question is ".$question->survey_qn_id;
										if( ($surveyDetails->getData('survey_id') == 1) && ($count == 10) && ($question->survey_qn_id ==1) )
										{
											echo "<span>Extremely Satisfied </span>";	
										}
										if( ($surveyDetails->getData('survey_id') == 1) && ($count == 10) && ($question->survey_qn_id ==2) )
										{
											echo "<span>Very Likely</span>";	
										}
										if( ($surveyDetails->getData('survey_id') == 1) && ($count == 10) && ($question->survey_qn_id ==5) )
										{
											echo "<span>Extremely Satisfied </span>";	
										}
										?>
                                  <?php endif; ?>
                                  <?php if( $ansType=="8"): ?>    
                                      <input type="checkbox" name="survey_values[<?php echo $question->survey_qn_id; ?>]" value="<?php echo $answer->survey_ans_id; ?>"/>
                                  <?php endif; ?>     
                              <?php $count++; endforeach; ?>
                                      
                          <?php if( $ansType=="9" ||  $ansType=="6"): ?>  
                             </select>
                          <?php endif; ?>
                          
                          <?php 
							//echo "Ans type is ".$ansType;
							if( $ansType=="3"): ?>  
								<?php
								if($surveyDetails->getData('survey_id') != 1){
								?>
                              <input type="text" name="survey_values[<?php echo $question->survey_qn_id; ?>]" value="" size="40"/>
							  <?php
								}else{
							  ?>
							   <textarea name="survey_values[<?php echo $question->survey_qn_id; ?>]" rows="8" cols="100"></textarea>
							   <?php
								}
							   ?>
                          <?php endif; ?>
                          
                          <?php if( $ansType=="4"): ?>    
                              <textarea name="survey_values[<?php echo $question->survey_qn_id; ?>]" rows="8" cols="100"></textarea>
                          <?php endif; ?> 
                      <?php $cnt++; ?>  
                      </div>    
            <?php endforeach; ?>
			<div style="display:none;">
                  <input type="hidden" id="survey_id" name="survey_id" value="<?php echo $surveyDetails->getData('survey_id'); ?>" />     
				  
				  Customer ID: <input type="text" name="customerId" value="<?php echo $_GET['customerId']?>">
				  Driver ID: <input type="text" name="driverId" value="<?php echo $_GET['driverId'];?>">
				  Picker ID: <input type="text" name="pickerId" value="<?php echo $_GET['pickerId'];?>">
				  Order ID: <input type="text" name="orderId" value="<?php echo $_GET['order'];?>">
				</div>
                  <div class="actions">
					<?php
						if($surveyDetails->getData('survey_id') == 1){
						?>
						<button class="button" title="Submit Survey" type="submit"><span><span><?php echo $this->__('Submit Survey') ?></span></span></button>
						<?php
						}else{
						?>
						<button class="button" title="Submit your Feedback" type="submit"><span><span><?php echo $this->__('Submit your Feedback') ?></span></span></button> 
						<?php	
						}
					?>
                    
                  </div>
            </form>
		<?php } else { ?>
		
		<div style="margin-top:10px;margin-bottom:15px;color:green;"> A survey has already been received for this order. Thank you! </div>
		
		<?php } ?>
		
        </div>
    </div>
</div>
<?php endif; ?>
