<?php /* @var $this Mage_Core_Block_Template */?>
<?php $currentAction = $this->getAction()->getFullActionName('/');?>
<form id="ugiftcert-form" action="<?php echo $this->getUrl('ugiftcert/checkout/add') ?>" method="post">
<div class="discount">
<h2><?php echo $this->__('Gift cards') ?></h2>
<?php			
		$collection = Mage::getBlockSingleton('checkout/cart_totals');	
		$total = $collection->getTotals();
		$subtotal = $total['subtotal']['value'];	
		//echo "<br/>Subtotal IS ".Mage::helper('checkout/cart')->getQuote()->getSubtotal();		?>
<div class="ugiftcert-form">
<label for="cert_code"><?php echo $this->__('Redeem gift card if you have one.') ?></label>
<input type="hidden" value="<?php echo $currentAction;?>" name="current_action"/>
<div class="input-box">
<input class="input-text" id="cert_code" name="cert_code" value="" />
</div>
<?php		
		$customerData = Mage::getSingleton('customer/session')->getCustomer();
							//echo "Customer Id is ".$customerData->getId();
							$customerId = $customerData->getId();
							$orders = Mage::getResourceModel("sales/order_collection")
                            ->addAttributeToSelect('customer_id')
                            ->addAttributeToSelect('customer_email')
                            ->addAttributeToSelect('increment_id');
		$sql= "SELECT * FROM mg_aw_sarp2_profile WHERE customer_id = '".$customerData->getId()."' AND `status` LIKE 'active'";
		$connection = Mage::getSingleton('core/resource')->getConnection('core_read');
		$results = $connection->fetchAll($sql);
		//echo "<pre>";
		//print_r($result);
			if($results){
			$jsonText = $results[0]['details'];
			$decodedText = html_entity_decode($jsonText);
			$orderArray = unserialize($decodedText);
			$itemID = $orderArray['subscription']['item']['subscription_type_id'];
			$premiumFlag = false;
			if($itemID == 1){
						//if($orderArray['order_item_info']['product_id'] == 25265){
						   //Basic 
				$basic = true;
				$premiumFlag = true;
				
			}
			if($itemID == 2){
				//if($orderArray['order_item_info']['product_id'] == 27592){
				// Premium Plus
				$premiumPlus = true;
				$premiumFlag = true;
			}
		}
		if($premiumFlag == 1){
			$minimum = 25;			
		}else{
			$minimum = 50;			
		}
		//echo "Premium flag is ".$premiumFlag;
		if($subtotal <$minimum){	
	
	?>					
	<div class="buttons-set">						 
	<button type="button" title="<?php echo $this->__('Apply Card') ?>" class="button subscription-coupon"	disabled="disabled" value="<?php echo $this->__('Apply Card') ?>">								<span><span><?php echo $this->__('Apply Card') ?></span></span></button><br/><br/>
	<span id="rewardpoints-needmore-msg">Total must be $<?php echo $minimum;?> for applying gift card</span>					 </div>
	<?php	
		}
		else{		
	?>
	<div class="buttons-set">
	<?php
	$cart = Mage::getModel('checkout/cart')->getQuote()->getItemsCollection();
	$my_val = $cart->getData();
	//echo $my_val[0]['product_id'];			
	if($my_val[0]['product_id'] == '25265')
	{
		?>
		<button type="button" title="<?php echo $this->__('Apply Card') ?>" class="button subscription-coupon"
		onclick="" value="<?php echo $this->__('Apply Card') ?>">
		<span><span><?php echo $this->__('Apply Card') ?></span></span></button>
		<?php
	}
	else
	{
		?>
		<button type="button" title="<?php echo $this->__('Apply Card') ?>" class="button"
		onclick="ugiftcertForm.submit()" value="<?php echo $this->__('Apply Card') ?>">
		<span><span><?php echo $this->__('Apply Card') ?></span></span></button>
		<?php
	}
	?>	
	<!-- <button type="button" title="<?php echo $this->__('Apply Card') ?>" class="button"
	onclick="ugiftcertForm.submit()" value="<?php echo $this->__('Apply Card') ?>">
	<span><span><?php echo $this->__('Apply Card') ?></span></span></button> -->
	</div>
	<?php				}			?>
</div>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
var ugiftcertForm = new VarienForm('ugiftcert-form');
ugiftcertForm.submit = function () {
	$('cert_code').addClassName('required-entry');
	return VarienForm.prototype.submit.bind(ugiftcertForm)();
}
jQuery(document).ready(function()
{
	jQuery(".subscription-coupon").click(function()
	{
		
		jQuery(".subscribe-notice").show();
		jQuery('body').animate({scrollTop:0}, 'slow');
		
	});
});
//]]>
</script>