<?php
/**
 * @see Mage_Adminhtml_Block_Sales_Items_Column_Name
 */
?>

<?php if ($_item = $this->getItem()): ?>
<?php
		
		$product = Mage::getModel('catalog/product');
		$productId = $product->getIdBySku($this->htmlEscape($this->getSku()));
		 $read= Mage::getSingleton('core/resource')->getConnection('core_read');
		 $value=$read->query("Select product_id  from mg_belvg_gifts_product WHERE product_id = '".$productId."' ");
		 $row = $value->fetch();
		 //echo "<pre>";
		// print_r($row);  
		
	?>
     <h5 class="title">
		<?php
			//echo "Product id is ".$productId;
			
			if( ($productId != '') && ($row['product_id'] == $productId) ){
			?>
				<span id="order_item_<?php echo $_item->getId() ?>_title"><?php echo "FREE PROMOTIONAL ITEM - ".$this->htmlEscape($_item->getName()) ?></span>
			<?php
			}else{
		?>
	<span id="order_item_<?php echo $_item->getId() ?>_title"><?php echo $this->htmlEscape($_item->getName()) ?></span>
		<?php
			}
		?>
	</h5>
	
    <div><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->htmlEscape($this->getSku()))); ?></div>
    <?php if ($this->getOrderOptions()): ?>
        <dl class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <dt><?php echo $_option['label'] ?></dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                <?php echo $this->getCustomizedOptionValue($_option); ?>
            <?php else: ?>
                <?php $_option = $this->getFormattedOption($_option['value']); ?>
                <?php echo $_option['value']; ?><?php if (isset($_option['remainder']) && $_option['remainder']): ?><span id="<?php echo $_dots = 'dots' . uniqid()?>"> ...</span><span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_option['remainder'] ?></span>
                    <script type="text/javascript">
                    $('<?php echo $_id ?>').hide();
                    $('<?php echo $_id ?>').hide();
                    $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
                    $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_dots?>').hide();});
                    $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});
                    $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_dots ?>').show();});
                    </script>
                <?php endif; ?>
            <?php endif; ?>
            </dd>
        <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <i title="<?php echo $this->helper('sales')->__('Description'); ?>"><?php echo $this->htmlEscape($_item->getDescription()) ?></i>
<?php endif; ?>
