<?php
/**
 * BelVG
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 
 * @category   Belvg
 * @package    Chameleon Mobile Theme
 * @copyright  Copyright (c) 2010 - 2012 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
/* @var $this Mage_Wishlist_Block_Customer_Wishlist */
?>
<?php

if (version_compare(Mage::getVersion(), '1.9', '>') && version_compare(Mage::getVersion(), '1.12', '<')) {
    include 'view_111.phtml';
} elseif (version_compare(Mage::getVersion(), '1.5', '<')) {
    include 'view_14.phtml';
} else {
    include 'view_17.phtml';
}

?>