<div class="testimonials-list">
    <?php if (is_null($this->getShowTitle()) || $this->getShowTitle()): ?>
        <div class="page-title" style="margin-top:10px;margin-bottom:15px;padding:10px;">
            <h1 style="color:#000;"><?php echo $this->__('Testimonials') ?></h1>
          <!--  <div class="submit-testimonial">
                <button class="button" onclick="setLocation('<?php echo $this->getUrl('testimonials/index/new'); ?>')">
                    <span><span><?php echo $this->__('Submit Your Testimonial') ?></span></span>
                </button>
            </div>-->
        </div>
    <?php endif ?>
    <div class="testimonials">