<?php
/**
* zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.zeonsolutions.com/shop/license-community.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento Community edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    base_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://www.zeonsolutions.com/shop/license-community.txt
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<?php if ($_product->getTypeId() == 'bundle'): ?>
    <div id="bundle-product-wrapper">
        <div id="bundleProduct">
        <?php endif; ?>
        <div class="product-view">
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" onsubmit="ajaxCart.addUpdate('ajaxcart/cart/add');return false;" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>
                <div class="product-essential">
                    <div class="product-shop">
                        <div class="product-main-info">
                            <div class="product-name">
                                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                            </div>
                            <?php echo $this->getChildHtml('product_type_data') ?>
                        </div>
                        <?php echo $this->getChildHtml('tierprices') ?>

                        <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildHtml('container1')): ?>
                            <div class="options-container-small">
                                <?php echo $this->getChildHtml('container1') ?>
                            </div>
                        <?php endif; ?>
                        <?php if ($_product->getShortDescription()): ?>
                            <div class="short-description std">
                                <h2><?php echo $this->__('Quick Overview') ?></h2>
                                <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="product-img-box">
                        <?php echo $this->getChildHtml('media') ?>
                    </div>
                </div>
                <div class="clearer"></div>
                <?php if ($_product->isSaleable() && $this->hasOptions() && ($this->getChildHtml('container2') || $this->getChildHtml('container3'))): ?>
                    <div class="options-container-big">
                        <fieldset id="product-options-wrapper" class="product-options">
                            <?php echo $this->getChildHtml('options_js') ?>
                            <?php if ($this->getChildHtml('container3')): ?>
                                <div id="options-container" class="bundle-option-container">
                                    <?php echo $this->getChildHtml('container3') ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($this->getChildHtml('container2')): ?>
                                <?php echo $this->getChildHtml('container2') ?>
                            <?php endif; ?>
                            <?php echo $this->getChildHtml('html_calendar') ?>
                        </fieldset>
                        <script type="text/javascript">
                            decorateGeneric($$('#product-options-wrapper dl'), ['last']);
                        </script>
                    </div>
                <?php endif; ?>
                <div class="product-options-bottom">
                    <?php if ($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                    <?php endif; ?>
                    <div class="clearer"></div>
                    <?php if ($_product->getTypeId() == 'bundle'): ?>
                        <?php echo $this->getChildHtml('bundle_prices') ?>
                    <?php else: ?>
                        <?php echo $this->getChildHtml('prices') ?>
                    <?php endif; ?>
                    <?php if ($this->hasRequiredOptions()): ?>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <?php endif; ?>
                </div>
            </form>
        </div>
        <?php if ($_product->getTypeId() == 'bundle'): ?>
        </div>
    </div>
<?php endif; ?>