<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Raf
 * @version    2.1.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if (!Mage::getSingleton('customer/session')->isLoggedIn() || !Mage::helper('awraf/config')->isInviteAllowed()): return; endif?>
<?php
    $buttonId = uniqid( rand(0, 1000) );
?>
<p class="raf-right"><button class="button btn-cart" id="referafriend-button<?php echo $buttonId;?>" type="button"><span><span id="invite_span2"><?php echo $this->__('Invite Friends') ?></span></span></button></p>

<p class= "raf_link_text" >
<?php echo 'OR send this link via email';?> </p>
 <input type="text" class="aw-raf-broadcastlink raf_link" id="aw-raf-broadcastlink" onclick="this.select()" value="<?php echo  $this->helper('awraf')->getReferrerLink();?>" readonly="readonly" />
	

<script type="text/javascript">
    document.observe('dom:loaded', function () {
        new Referafriend($('referafriend-button<?php echo $buttonId;?>'), '<?php echo $this->helper('awraf')->getReferafriendUrl() ?>');
    });
</script>