<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Raf
 * @version    2.1.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_invites = $this->getInvites(); ?>
<div id ="ref_title" class="page-title">
    <h1><?php echo $this->__('PrestoPayback Program') ?></h1>
	<h4><?php echo $this->__('Refer your friends/family, and accumulate discount dollars! It’s easy:') ?> </h4>
	<p><?php echo $this->__('Invite your friends & family using the link below, and you will receive $2 off credits for every $100 that they spend! The next time you make a purchase, you will have the option to use the discount dollars when you check out!') ?> </P>
</div>
<div class="aw-raf-statistics">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('PrestoPayback Program'); ?></h2>
        <?php if ($_invites->getSize()): ?>
            <?php echo $this->getChildHtml('awraf.stats.pager'); ?>
            <div class="aw-raf-table-wrapper">
                <table cellspacing="0" class="data-table" id="referred-friends-table">
                    <thead>
                        <tr>
                            <th><?php echo $this->__('Customer Email') ?></th>
                            <th><?php echo $this->__('Signed up') ?></th>
                            <th><?php echo $this->__('Confirmed') ?></th>
                            <th><?php echo $this->__('Purchased') ?></th>
                         <!--   <th><?php //echo $this->__('Purchased Amount') ?></th>>-->
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_invites as $_invite): ?>
                            <tr>
                                <td><?php echo $_invite->getEmail() ?></td>
                                <td><?php echo $_invite->getCustomerId() ? $this->__('Yes') : $this->__('No') ?></td>
								
                                <td><?php echo $this->isConfirmed($_invite) ? $this->__('Yes') : $this->__('No') ?></td>
								
                           <!--    <td class="a-right"><?php// echo (int) $_invite->getItemsPurchased() ?></td> -->
							   
							 <!-- <td class="a-right"><?php //echo $this->formatAmount($_invite->getAmountPurchased()) ?></td> 	-->	

<!-------- Xoom- Purchase y/n------------>							
							
						<td ><?php echo (int) $_invite->getItemsPurchased() > 0 ? $this->__('Yes') : $this->__('No') ?></td>
						
						<!--	<td class="a-right"><?php //echo (int) $_invite->getAmountPurchased() > 0 ? $this->__('Yes') : $this->__('No') ?></td>	-->
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('referred-friends-table')</script>
            </div>
            <?php echo $this->getChildHtml('awraf.stats.pager'); ?>
        <?php else: ?>
            <p><?php echo $this->__('You have no referred friends.'); ?></p>
        <?php endif ?>

        <div class="col2-set">
            <div class="col-1">
                <div class="fieldset">
                    <h2 class="legend"><?php echo $this->__('Accumulated Discount Dollars'); ?></h2>
                    <ol>
                        <li class="awraf-balance-item item">
                            <?php echo $this->getActiveBalance(); ?>
                        </li>
                    </ol>
                </div>
            </div>
			<!--
            <div class="col-2">
                <div class="fieldset">
                    <h2 class="legend"><?php //echo $this->__('Active Discount'); ?></h2>
                    <ol>
                        <li class="awraf-balance-item item">
                            <?php //echo (float) $this->getActiveDiscount(); ?>%
                        </li>
                    </ol>
                </div>
            </div> --->
			
        </div>

       <?php if ($this->isInviteAllowed()): ?>
            <div id= "fieldset_invite" class="fieldset">
              <h2 class="legend"><?php echo $this->__('Invite Form'); ?></h2>
              <?php echo $this->getChildHtml('awraf.invite_button'); ?>          
          	
       <?php endif; ?>
	   </div>
	     <?php echo $this->getChildHtml('awraf.broad.cast.link') ?>
		
    </div>
</div>

<style>
.raf-right {
margin-bottom: 10px;
width: 25%;
float:left;
}

.raf_link {
margin-bottom: 10px;
width: 75%;
float:right;
}

#fieldset_invite{
padding: 22px 25px 25px 13px;
}

.aw-raf-statistics .fieldset{
padding: 22px 25px 12px 13px;
}

#ref_title h4{
color: #e76200;
}

#invite_span2{
padding: 0 15px;
}

.raf_link_text{
color: #e76200;
}
</style>
