<div class="faq">
	<q>How much does the service cost?</q>
	<div class="ans">Your order will carry a small fee to cover the cost of delivery. There is also a minimum order amount of $50. The delivery fees are as follows:

		<ul>
			<li>Order value $50-74.99: $9.95</li>
			<li>Order value $75-99.99: $8.95</li>
			<li>Order value $100+: $7.95</li>
    	</ul>
    </div>
    
    <q>When will my order be delivered?</q>
	<div class="ans">PrestoFresh offers 2 hour delivery windows every day of the week!When you check out, you will be able to choose the window that works best for you.</div>
	
    <q>I've heard grocery delivery is an expensive service; is this true?</q>
	<div class="ans">We strive to keep our prices on par with those that you find at other stores in the area. Individual items may be slightly more or less expensive compared with other stores, but we think you'll find that they average out about the same.</div>
	
    <q>Is it possible to save money shopping with PrestoFresh?</q>
	<div class="ans">Shopping with PrestoFresh will enable you to save money in several ways! First, as you shop, you can see the items you have selected and your running total bill as you go! As a result, you can better manage your budget while you shop and avoid surprises when you check out. Furthermore, you can shop from the comfort of your home, allowing you to avoid impulse buys and confirm the items that you need before you make a purchase. Lastly, PrestoFresh will be periodically put items on sale and/or offer promotions. Keep an eye out!</div>
    
    <q>What do you carry?</q>
	<div class="ans">PrestoFresh carries most of the same products you would find at your local grocery store, plus more! You will also find products from some local shops, markets, and vendors.</div>
    
    <q>How do you ensure freshness and high quality?</q>
	<div class="ans">For starters, we select items for an order at the last possible moment. The items are then prepared for delivery but placed in appropriate cold storage to maintain the correct temperature to ensure quality until you receive your order.</div>
	
    <q>What if I am not available during the delivery window I selected?</q>
	<div class="ans">If it turns out that you will not be available during the time you scheduled your order, please email us at support@prestofreshgrocery.com. We will make every attempt to work with you, but please note that an order correction fee may apply. If you are not present when we deliver your order and you would like a redeliver, a $10 re-delivery fee will apply.</div> 


	<q>What do I do if I'm not happy with my service?</q>
	<div class="ans">Your satisfaction is our priority. If you are not satisfied, just let us know - we commit to working with you to make sure you are delighted with our service!</div>
    
    <q>Ok, I'm ready - how do I get started?</q>
	<div class="ans">It's easy! Just sign up (no cost to you!) and start shopping - that's all it takes.</div>
</div>    
<script type="text/javascript">
jQuery(function(){
	jQuery('.ans').hide();
	
	jQuery('q').click(function(){
		jQuery('.ans').hide();
		jQuery(this).next('div.ans').fadeToggle(300);
	});
});
</script>